"""Local/On-premise."""
import os
import subprocess
import typing
from typing import Dict, Iterator, List, Optional, Tuple
import yaml

from sky import clouds

if typing.TYPE_CHECKING:
    # Renaming to avoid shadowing variables.
    from sky import resources as resources_lib

_LOCAL_YAML_PATH = '~/.sky/local/{}.yml'


def _run_output(cmd):
    proc = subprocess.run(cmd,
                          shell=True,
                          check=True,
                          stderr=subprocess.PIPE,
                          stdout=subprocess.PIPE)
    return proc.stdout.decode('ascii')


class Local(clouds.Cloud):
    """A local/on-premise cloud, also acting as a local cluster.

    This Cloud has the following special treatment of Cloud concepts:

    - Catalog: Does not have service catalog.
    - Region: Only one region ('Local' region).
    - Cost: Treats all compute/egress as free.
    - Instance types: Only one instance type ('on-prem' instance type).
    - Cluster: Each Local cloud corresponds to exactly 1 cluster.
    - Credentials: No checking is done (in `sky check`) and users must
        provide their own credentials instead of Sky autogenerating
        cluster credentials.
    """

    LOCAL_REGION = clouds.Region('Local')
    _REPR = 'Local'
    _regions: List[clouds.Region] = [LOCAL_REGION]

    def __init__(self, cluster_name: str = None):
        if cluster_name is not None:
            self.local_cluster_name = cluster_name
        else:
            # Default local name is set for task.set_resources method.
            self.local_cluster_name = 'default-local-name'

    @classmethod
    def regions(cls):
        return cls._regions

    @classmethod
    def region_zones_provision_loop(
        cls,
        *,
        instance_type: Optional[str] = None,
        accelerators: Optional[Dict[str, int]] = None,
        use_spot: bool,
    ) -> Iterator[Tuple[clouds.Region, List[clouds.Zone]]]:
        del accelerators  # unused
        assert instance_type is None and not use_spot
        for region in cls.regions():
            yield region, region.zones

    #### Normal methods ####

    def instance_type_to_hourly_cost(self, instance_type: str, use_spot: bool):
        # On-prem machines on Sky are assumed free
        # (minus electricity/utility bills).
        return 0.0

    def accelerators_to_hourly_cost(self, accelerators, use_spot):
        # Hourly cost of accelerators is 0 for local cloud.
        return 0

    def get_egress_cost(self, num_gigabytes: float):
        # Egress cost from a local cluster is assumed to be 0.
        return 0.0

    def __repr__(self):
        return self.local_cluster_name

    def is_same_cloud(self, other: clouds.Cloud):
        # Returns true if the two clouds are the same cloud type
        # and has the matching cluster name.
        return isinstance(
            other,
            Local) and self.local_cluster_name == other.local_cluster_name

    @classmethod
    def get_default_instance_type(cls) -> str:
        # There is only "1" instance type for local cloud: on-prem
        return 'on-prem'

    @classmethod
    def get_accelerators_from_instance_type(
        cls,
        instance_type: str,
    ) -> Optional[Dict[str, int]]:
        # This function is not called, as local cloud does not have service
        # catalog.
        raise NotImplementedError

    def make_deploy_resources_variables(self,
                                        resources: 'resources_lib.Resources'):
        return {}

    def get_feasible_launchable_resources(self,
                                          resources: 'resources_lib.Resources'):
        # The entire local cluster's resources is considered launchable, as the
        # check for task resources is deferred later.
        # The check for task resources meeting cluster resources is run in
        # cloud_vm_ray_backend._check_task_resources_smaller_than_cluster.
        return [resources], []

    def check_credentials(self) -> Tuple[bool, Optional[str]]:
        # clouds.Local is not called in `sky check`
        # (not part of global registry).
        raise NotImplementedError

    def get_credential_file_mounts(self) -> Tuple[Dict[str, str], List[str]]:
        # Credentials are not autogenerated by Sky.
        # Credentials are instead provided by the user, hence this method
        # returns an empty dict and list.
        return {}, []

    def instance_type_exists(self, instance_type: str) -> bool:
        # Checks if instance_type matches on-prem, the only instance type for
        # local cloud.
        return instance_type == self.get_default_instance_type()

    def region_exists(self, region: str) -> bool:
        # Returns true if the region name is same as Local cloud's
        # one and only region: 'Local'.
        return region == Local.LOCAL_REGION.name

    @staticmethod
    def get(cluster: str) -> Optional['Local']:
        """Gets the local cluster object."""
        return clouds.Local(cluster)

    def get_local_ips(self) -> List[str]:
        """Returns IP addresses of the local cluster."""
        cluster = self.local_cluster_name
        local_cluster_path = os.path.expanduser(
            _LOCAL_YAML_PATH.format(cluster))
        try:
            with open(local_cluster_path, 'r') as f:
                config = yaml.safe_load(f)
        except OSError as e:
            raise ValueError(
                f'Could not open/read file: {local_cluster_path}') from e

        ips = config['cluster']['ips']
        if isinstance(ips, str):
            ips = [ips]
        return ips
