#!/usr/bin/env python3
"""GRPO Trainer for RLHF math training.

This trainer orchestrates the RLHF pipeline by:
1. Fetching prompts from data-server
2. Generating responses via rollout-server (SGLang)
3. Computing rewards via reward-server
4. Storing experiences in replay-buffer
5. Updating the policy using GRPO (Group Relative Policy Optimization)
6. Pushing the updated policy back to the rollout-server every N steps,
   so subsequent samples are generated by the latest policy.

GRPO is a simplified variant of PPO that doesn't require a critic model,
making it popular for math/code tasks with verifiable rewards.

Usage:
    python trainer.py \
        --data-server localhost:8000 \
        --rollout-server localhost:8001 \
        --reward-server localhost:8002 \
        --replay-buffer localhost:8003 \
        --num-epochs 3
"""

import argparse
import concurrent.futures
from dataclasses import dataclass
import time
from typing import List, Optional

from accelerate import Accelerator
import httpx
import torch
from transformers import AutoModelForCausalLM
from transformers import AutoTokenizer


@dataclass
class TrainingConfig:
    """Training configuration."""
    data_server: str
    rollout_server: str
    reward_server: str
    replay_buffer: Optional[str] = None
    model_name: str = "Qwen/Qwen2.5-0.5B-Instruct"
    batch_size: int = 4
    num_epochs: int = 3
    steps_per_epoch: int = 100
    learning_rate: float = 1e-6
    max_new_tokens: int = 512
    temperature: float = 0.7
    num_samples_per_prompt: int = 4  # For GRPO, generate multiple samples
    kl_coef: float = 0.01
    clip_range: float = 0.2
    use_replay_buffer: bool = True  # Whether to use replay buffer for training
    # Policy sync: push updated weights to the rollout server every N steps.
    # Requires a path that both trainer and rollout-server can read/write
    # (e.g., a shared PVC or bucket mounted on both tasks).
    policy_sync_path: Optional[str] = None
    policy_sync_interval: int = 10
    policy_sync_servers: Optional[List[str]] = None
    policy_sync_max_attempts: int = 30
    policy_sync_retry_interval: int = 10


class RLHFTrainer:
    """GRPO trainer that coordinates with external services."""

    def __init__(self, config: TrainingConfig):
        self.config = config
        self.accelerator = Accelerator()

        # HTTP clients for services
        self.http_client = httpx.Client(timeout=120.0)

        # Load model and tokenizer
        if self.accelerator.is_main_process:
            print(f"Loading model: {config.model_name}")

        self.tokenizer = AutoTokenizer.from_pretrained(config.model_name)
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token

        self.model = AutoModelForCausalLM.from_pretrained(
            config.model_name, torch_dtype=torch.bfloat16, device_map="auto")

        # Optimizer
        self.optimizer = torch.optim.AdamW(self.model.parameters(),
                                           lr=config.learning_rate)

        # Prepare with accelerator
        self.model, self.optimizer = self.accelerator.prepare(
            self.model, self.optimizer)

        # Statistics
        self.total_steps = 0
        self.total_rewards = 0.0

    def save_static_policy_sync_assets(self):
        """Save static policy files used by later weight syncs."""
        if not self.config.policy_sync_path:
            return
        if not self.accelerator.is_main_process:
            return
        self.tokenizer.save_pretrained(self.config.policy_sync_path)

    def wait_for_services(self,
                          max_retries: int = 30,
                          retry_interval: int = 10):
        """Wait for all services to be available."""
        services = [
            ("data-server", f"http://{self.config.data_server}/health"),
            ("rollout-server", f"http://{self.config.rollout_server}/health"),
            ("reward-server", f"http://{self.config.reward_server}/health"),
        ]
        if self.config.replay_buffer:
            services.append(
                ("replay-buffer", f"http://{self.config.replay_buffer}/health"))

        for name, url in services:
            if self.accelerator.is_main_process:
                print(f"Waiting for {name} at {url}...")

            for attempt in range(max_retries):
                try:
                    response = self.http_client.get(url)
                    if response.status_code == 200:
                        if self.accelerator.is_main_process:
                            print(f"  {name} is ready!")
                        break
                except Exception as e:
                    pass

                if attempt < max_retries - 1:
                    time.sleep(retry_interval)
            else:
                raise RuntimeError(
                    f"Service {name} not available after {max_retries} retries")

    def fetch_prompts(self, batch_size: int) -> List[dict]:
        """Fetch a batch of prompts from data server."""
        url = f"http://{self.config.data_server}/prompts"
        response = self.http_client.get(url, params={"batch_size": batch_size})
        response.raise_for_status()
        data = response.json()
        return data["prompts"]

    def generate_responses(self, prompts: List[str]) -> List[str]:
        """Generate responses using the rollout server (SGLang)."""
        url = f"http://{self.config.rollout_server}/v1/completions"

        responses = []
        for prompt in prompts:
            payload = {
                "model": self.config.model_name,
                "prompt": prompt,
                "max_tokens": self.config.max_new_tokens,
                "temperature": self.config.temperature,
                "n": 1,
            }
            try:
                response = self.http_client.post(url, json=payload)
                response.raise_for_status()
                data = response.json()
                text = data["choices"][0]["text"]
                responses.append(text)
            except Exception as e:
                print(f"Error generating response: {e}")
                responses.append("")

        return responses

    def compute_rewards(self, prompts: List[str], responses: List[str],
                        ground_truths: List[str]) -> List[float]:
        """Compute rewards using the reward server."""
        url = f"http://{self.config.reward_server}/batch_reward"

        items = [{
            "prompt": p,
            "response": r,
            "ground_truth": gt
        } for p, r, gt in zip(prompts, responses, ground_truths)]

        response = self.http_client.post(url, json={"items": items})
        response.raise_for_status()
        data = response.json()

        return [r["reward"] for r in data["rewards"]]

    def store_experiences(self, prompts: List[str], responses: List[str],
                          rewards: List[float], ground_truths: List[str]):
        """Store experiences in the replay buffer."""
        if not self.config.replay_buffer:
            return

        url = f"http://{self.config.replay_buffer}/add"
        experiences = [{
            "prompt": p,
            "response": r,
            "reward": rw,
            "ground_truth": gt
        } for p, r, rw, gt in zip(prompts, responses, rewards, ground_truths)]

        try:
            response = self.http_client.post(url,
                                             json={"experiences": experiences})
            response.raise_for_status()
        except Exception as e:
            print(f"Warning: Failed to store experiences in replay buffer: {e}")

    def sample_from_replay_buffer(self,
                                  batch_size: int) -> Optional[List[dict]]:
        """Sample experiences from the replay buffer."""
        if not self.config.replay_buffer:
            return None

        url = f"http://{self.config.replay_buffer}/sample"
        try:
            response = self.http_client.post(url,
                                             json={
                                                 "batch_size": batch_size,
                                                 "prioritized": True
                                             })
            response.raise_for_status()
            data = response.json()
            if data["experiences"]:
                return data["experiences"]
        except Exception as e:
            print(f"Warning: Failed to sample from replay buffer: {e}")
        return None

    def get_replay_buffer_stats(self) -> Optional[dict]:
        """Get replay buffer statistics."""
        if not self.config.replay_buffer:
            return None

        url = f"http://{self.config.replay_buffer}/stats"
        try:
            response = self.http_client.get(url)
            response.raise_for_status()
            return response.json()
        except Exception as e:
            return None

    def compute_grpo_loss(self, prompts: List[str], responses: List[str],
                          rewards: List[float]) -> torch.Tensor:
        """Compute GRPO loss for policy update.

        GRPO uses group-relative advantages: for each prompt, we compare
        the reward of each response to the mean reward of all responses
        for that prompt.
        """
        # Tokenize prompts and responses together
        full_texts = [p + r for p, r in zip(prompts, responses)]
        encodings = self.tokenizer(full_texts,
                                   return_tensors="pt",
                                   padding=True,
                                   truncation=True,
                                   max_length=1024).to(self.accelerator.device)

        # Get prompt lengths for masking
        prompt_encodings = self.tokenizer(prompts,
                                          return_tensors="pt",
                                          padding=True,
                                          truncation=True,
                                          max_length=512)
        prompt_lengths = prompt_encodings.attention_mask.sum(dim=1)

        # Forward pass
        outputs = self.model(**encodings, labels=encodings.input_ids)

        # Compute per-token log probabilities
        logits = outputs.logits[:, :-1, :]
        labels = encodings.input_ids[:, 1:]
        log_probs = torch.nn.functional.log_softmax(logits, dim=-1)
        token_log_probs = torch.gather(log_probs, 2,
                                       labels.unsqueeze(-1)).squeeze(-1)

        # Mask out prompt tokens (only count response tokens)
        response_mask = torch.zeros_like(token_log_probs)
        for i, plen in enumerate(prompt_lengths):
            response_mask[i, plen - 1:] = 1.0
        response_mask = response_mask * encodings.attention_mask[:, 1:]

        # Sum log probs for each response
        response_log_probs = (token_log_probs * response_mask).sum(dim=1)

        # Convert rewards to tensor and compute advantages
        rewards_tensor = torch.tensor(rewards,
                                      device=self.accelerator.device,
                                      dtype=torch.float32)

        # GRPO: normalize rewards within batch (group-relative)
        mean_reward = rewards_tensor.mean()
        std_reward = rewards_tensor.std(unbiased=False) + 1e-8
        advantages = (rewards_tensor - mean_reward) / std_reward

        # Policy gradient loss (negative because we maximize reward)
        loss = -(response_log_probs * advantages).mean()

        return loss

    def sync_policy_to_rollout(self):
        """Push the freshly-updated policy weights to the rollout server.

        Without this, the rollout server keeps generating samples with the
        original policy and learning never propagates back. The trainer
        saves the current weights to a path that's shared with the rollout
        task (via a PVC, shared bucket, or other shared filesystem), then
        calls SGLang's ``update_weights_from_disk`` endpoint to reload them
        in place. SGLang's KV cache is flushed afterwards so subsequent
        generations use the new policy.
        """
        if not self.config.policy_sync_path:
            return
        if not self.accelerator.is_main_process:
            return

        # 1. Save the latest weights to the shared path.
        unwrapped = self.accelerator.unwrap_model(self.model)
        unwrapped.save_pretrained(self.config.policy_sync_path,
                                  safe_serialization=True)

        # 2. Tell rollout backend(s) to load the new weights and flush KV cache.
        sync_servers = self.config.policy_sync_servers or [
            self.config.rollout_server
        ]
        errors = []
        with concurrent.futures.ThreadPoolExecutor(
                max_workers=len(sync_servers)) as executor:
            future_to_server = {
                executor.submit(self._sync_policy_to_server, server): server
                for server in sync_servers
            }
            for future in concurrent.futures.as_completed(future_to_server):
                server = future_to_server[future]
                try:
                    future.result()
                except Exception as e:
                    errors.append(f"{server}: {e}")

        if errors:
            raise RuntimeError(
                "Failed to sync policy weights to rollout backend(s): " +
                "; ".join(errors))

    def _sync_policy_to_server(self, server: str):
        base_url = self._base_url(server)
        last_error: Optional[Exception] = None
        max_attempts = max(1, self.config.policy_sync_max_attempts)
        retry_interval = max(0, self.config.policy_sync_retry_interval)
        with httpx.Client() as client:
            for attempt in range(1, max_attempts + 1):
                try:
                    r = client.post(
                        f"{base_url}/update_weights_from_disk",
                        json={"model_path": self.config.policy_sync_path},
                        timeout=300.0)
                    r.raise_for_status()
                    r = client.post(f"{base_url}/flush_cache", timeout=30.0)
                    r.raise_for_status()
                    print(f"[policy-sync] step {self.total_steps}: pushed "
                          f"weights to {server}")
                    return
                except Exception as e:
                    last_error = e
                    if attempt == max_attempts:
                        break
                    print(f"[policy-sync] step {self.total_steps}: waiting "
                          f"for {server} to recover after attempt "
                          f"{attempt}/{max_attempts}: {e}")
                    time.sleep(retry_interval)

        raise RuntimeError(last_error)

    @staticmethod
    def _base_url(server: str) -> str:
        server = server.rstrip("/")
        if server.startswith("http://") or server.startswith("https://"):
            return server
        return f"http://{server}"

    def train_step(self) -> dict:
        """Execute one training step."""
        self.model.train()

        # 1. Fetch prompts
        prompt_data = self.fetch_prompts(self.config.batch_size)
        prompts = [p["prompt"] for p in prompt_data]
        ground_truths = [p["ground_truth"] for p in prompt_data]

        # 2. Generate responses
        responses = self.generate_responses(prompts)

        # 3. Compute rewards
        rewards = self.compute_rewards(prompts, responses, ground_truths)

        # 4. Store experiences in replay buffer
        self.store_experiences(prompts, responses, rewards, ground_truths)

        # 5. Compute loss and update with fresh experiences
        loss = self.compute_grpo_loss(prompts, responses, rewards)

        self.optimizer.zero_grad()
        self.accelerator.backward(loss)
        self.optimizer.step()

        # 6. Optionally do additional update with replay buffer samples
        replay_loss = None
        if self.config.use_replay_buffer and self.config.replay_buffer:
            replay_experiences = self.sample_from_replay_buffer(
                self.config.batch_size)
            if replay_experiences and len(replay_experiences) >= 2:
                replay_prompts = [e["prompt"] for e in replay_experiences]
                replay_responses = [e["response"] for e in replay_experiences]
                replay_rewards = [e["reward"] for e in replay_experiences]

                replay_loss = self.compute_grpo_loss(replay_prompts,
                                                     replay_responses,
                                                     replay_rewards)
                self.optimizer.zero_grad()
                self.accelerator.backward(replay_loss)
                self.optimizer.step()

        # Update statistics
        self.total_steps += 1
        mean_reward = sum(rewards) / len(rewards)
        self.total_rewards += mean_reward

        result = {
            "loss": loss.item(),
            "mean_reward": mean_reward,
            "accuracy": sum(1 for r in rewards if r > 0) / len(rewards),
            "num_samples": len(prompts)
        }
        if replay_loss is not None:
            result["replay_loss"] = replay_loss.item()
        return result

    def train(self):
        """Run the full training loop."""
        if self.accelerator.is_main_process:
            print("=" * 60)
            print("GRPO Training for Math")
            print("=" * 60)
            print(f"Model: {self.config.model_name}")
            print(f"Batch size: {self.config.batch_size}")
            print(f"Epochs: {self.config.num_epochs}")
            print(f"Steps per epoch: {self.config.steps_per_epoch}")
            print(f"Learning rate: {self.config.learning_rate}")
            print("=" * 60)

        # Wait for services
        self.wait_for_services()
        self.save_static_policy_sync_assets()

        # Training loop
        for epoch in range(self.config.num_epochs):
            epoch_rewards = []
            epoch_losses = []

            for step in range(self.config.steps_per_epoch):
                metrics = self.train_step()
                epoch_rewards.append(metrics["mean_reward"])
                epoch_losses.append(metrics["loss"])

                # Push the updated policy back to the rollout server so the
                # next batch of samples reflects the latest weights.
                interval = self.config.policy_sync_interval
                if (self.config.policy_sync_path and
                        self.total_steps % interval == 0):
                    self.sync_policy_to_rollout()

                if self.accelerator.is_main_process and step % 10 == 0:
                    print(f"Epoch {epoch+1}/{self.config.num_epochs} | "
                          f"Step {step+1}/{self.config.steps_per_epoch} | "
                          f"Loss: {metrics['loss']:.4f} | "
                          f"Reward: {metrics['mean_reward']:.4f} | "
                          f"Accuracy: {metrics['accuracy']:.2%}")

            # Epoch summary
            if self.accelerator.is_main_process:
                mean_epoch_reward = sum(epoch_rewards) / len(epoch_rewards)
                mean_epoch_loss = sum(epoch_losses) / len(epoch_losses)
                print(f"\n=== Epoch {epoch+1} Complete ===")
                print(f"Mean Reward: {mean_epoch_reward:.4f}")
                print(f"Mean Loss: {mean_epoch_loss:.4f}")

                # Print replay buffer stats
                buffer_stats = self.get_replay_buffer_stats()
                if buffer_stats:
                    print(
                        f"Replay Buffer: {buffer_stats['size']}/"
                        f"{buffer_stats['capacity']} "
                        f"(avg_reward: {buffer_stats['avg_reward']:.4f}, "
                        f"positive_ratio: {buffer_stats['positive_ratio']:.2%})"
                    )
                print()

        if self.accelerator.is_main_process:
            print("=" * 60)
            print("Training Complete!")
            print(f"Total steps: {self.total_steps}")
            print(
                f"Average reward: {self.total_rewards / self.total_steps:.4f}")
            print("=" * 60)


def main():
    parser = argparse.ArgumentParser(description="GRPO Trainer for RLHF")
    parser.add_argument("--data-server",
                        type=str,
                        required=True,
                        help="Data server address (host:port)")
    parser.add_argument("--rollout-server",
                        type=str,
                        required=True,
                        help="Rollout server address (host:port)")
    parser.add_argument("--reward-server",
                        type=str,
                        required=True,
                        help="Reward server address (host:port)")
    parser.add_argument("--replay-buffer",
                        type=str,
                        default=None,
                        help="Replay buffer address (host:port)")
    parser.add_argument("--model",
                        type=str,
                        default="Qwen/Qwen2.5-0.5B-Instruct",
                        help="Model name or path")
    parser.add_argument("--batch-size",
                        type=int,
                        default=4,
                        help="Training batch size")
    parser.add_argument("--num-epochs",
                        type=int,
                        default=3,
                        help="Number of training epochs")
    parser.add_argument("--steps-per-epoch",
                        type=int,
                        default=100,
                        help="Number of training steps per epoch")
    parser.add_argument("--learning-rate",
                        type=float,
                        default=1e-6,
                        help="Learning rate")
    parser.add_argument("--policy-sync-path",
                        type=str,
                        default=None,
                        help="Shared path (PVC/bucket mounted on both trainer "
                        "and rollout-server). When set, the trainer saves "
                        "the updated policy here and asks the rollout "
                        "server to reload it after every "
                        "--policy-sync-interval steps.")
    parser.add_argument("--policy-sync-interval",
                        type=int,
                        default=10,
                        help="Number of training steps between policy syncs "
                        "to the rollout server.")
    parser.add_argument("--policy-sync-servers",
                        type=str,
                        default=None,
                        help="Comma-separated rollout backend addresses for "
                        "policy reloads.")
    parser.add_argument("--policy-sync-max-attempts",
                        type=int,
                        default=30,
                        help="Maximum policy sync attempts per rollout "
                        "backend before failing.")
    parser.add_argument("--policy-sync-retry-interval",
                        type=int,
                        default=10,
                        help="Seconds to wait between policy sync retry "
                        "attempts.")
    args = parser.parse_args()
    policy_sync_servers = None
    if args.policy_sync_servers:
        policy_sync_servers = [
            server.strip()
            for server in args.policy_sync_servers.split(",")
            if server.strip()
        ]

    config = TrainingConfig(
        data_server=args.data_server,
        rollout_server=args.rollout_server,
        reward_server=args.reward_server,
        replay_buffer=args.replay_buffer,
        model_name=args.model,
        batch_size=args.batch_size,
        num_epochs=args.num_epochs,
        steps_per_epoch=args.steps_per_epoch,
        learning_rate=args.learning_rate,
        policy_sync_path=args.policy_sync_path,
        policy_sync_interval=args.policy_sync_interval,
        policy_sync_servers=policy_sync_servers,
        policy_sync_max_attempts=args.policy_sync_max_attempts,
        policy_sync_retry_interval=args.policy_sync_retry_interval,
    )

    trainer = RLHFTrainer(config)
    trainer.train()


if __name__ == "__main__":
    main()
