services:
  test:
    build:
      context: .
      target: test
      args:
        INSTALL_FROM_SOURCE: "true"
    working_dir: /skypilot
    volumes:
      - .:/skypilot
    environment:
      SKYPILOT_DEV: "1"
      SKYPILOT_DISABLE_USAGE_COLLECTION: "1"
      SKYPILOT_SKIP_CLOUD_IDENTITY_CHECK: "1"
    entrypoint: ["pytest"]
