apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-09-17T05:29:04Z"
  generation: 1
  name: debug-api-server
  namespace: skypilot
  resourceVersion: "1758086952211743017"
  uid: cfddf873-8b69-4e75-9409-c681d51ef0be
spec:
  automountServiceAccountToken: true
  containers:
  - args:
    - /bin/sh
    - -c
    - |
      set -e

      # Run commands before deploying the API server, e.g. installing an admin policy.
      # Refer to https://docs.skypilot.co/en/latest/cloud-setup/policy.html for more details about admin policy.
      # Remember to set the admin policy in the config section below.
      echo "Pre-deploy hook"

      # Uncomment the following lines to install the admin policy

      # echo "Installing admin policy"
      # pip install git+https://github.com/michaelvll/admin-policy-examples
      mkdir -p /root/.sky
      # When the config.yaml is a symlink, it should be from the old API
      # server code. We remove the symlink and copy the ConfigMap config to
      # PVC location for backward compatibility.
      # TODO(zhwu): remove this after 0.12.0.
      if [ -L /root/.sky/config.yaml ]; then
        echo "Config.yaml is a symlink to ConfigMap config, deleting symlink"
        rm /root/.sky/config.yaml
      fi
      # Initialize the SkyPilot config.
      if [ -s /root/.sky/config.yaml ]; then
        # If the config.yaml is not empty, sync the PVC config to ConfigMap
        python3 -c "from sky.utils.kubernetes import config_map_utils; config_map_utils.initialize_configmap_sync_on_startup('~/.sky/config.yaml')"
      else
        # If the config.yaml is empty, we initialize the config on PVC with
        # user specified config.
        cp /var/skypilot/config/config.yaml /root/.sky/config.yaml
      fi
      # Nebius credentials mounting
      # Since the ~/.nebius directory is also used by the Nebius CLI, we mount the credentials to /root/.nebius_credentials
      # and create a symlink to /root/.nebius. This cannot be done in the init container because the Nebius CLI needs read-write access to ~/.nebius.

      tail -f /dev/null
      if sky api start -h | grep -q -- "--foreground"; then
        exec sky api start --deploy --foreground
      else
        # For backward compatibility, run in background if --foreground is not supported.
        # TODO(aylei): this will be dropped in 0.11.0.
        if sky api start --deploy; then
          tail -n+0 -f /root/.sky/api_server/server.log
        else
          cat /root/.sky/api_server/server.log
        fi
      fi
    command:
    - tini
    - --
    env:
    - name: SKYPILOT_DEV
      value: "true"
    - name: SKYPILOT_RELEASE_NAME
      value: skypilot-alpha
    - name: ENABLE_SERVICE_ACCOUNTS
      value: "true"
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /root/gcp-cred.json
    - name: PYTHONASYNCIODEBUG
      value: "1"
    - name: SKYPILOT_DB_CONNECTION_URI
      valueFrom:
        secretKeyRef:
          key: connection_string
          name: skypilot-db-connection-uri
    - name: SKYPILOT_GRACE_PERIOD_SECONDS
      value: "60"
    - name: SKYPILOT_APISERVER_UUID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    - name: SKY_API_SERVER_METRICS_ENABLED
      value: "true"
    - name: SKYPILOT_AUTH_OAUTH2_PROXY_ENABLED
      value: "true"
    - name: SKYPILOT_AUTH_OAUTH2_PROXY_BASE_URL
      value: http://skypilot-alpha-oauth2-proxy:4180
    - name: SKYPILOT_POD_CPU_CORE_LIMIT
      valueFrom:
        resourceFieldRef:
          containerName: skypilot-api
          divisor: "0"
          resource: requests.cpu
    - name: SKYPILOT_POD_MEMORY_BYTES_LIMIT
      valueFrom:
        resourceFieldRef:
          containerName: skypilot-api
          divisor: "0"
          resource: requests.memory
    - name: IS_SKYPILOT_SERVER
      value: "true"
    image: berkeleyskypilot/skypilot-api-test:20250917043353
    imagePullPolicy: Always
    name: skypilot-api
    ports:
    - containerPort: 46580
      protocol: TCP
    - containerPort: 9090
      name: metrics
      protocol: TCP
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "4"
        memory: 8Gi
    securityContext:
      capabilities:
        add:
        - ALL
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/skypilot/config
      name: skypilot-config
    - mountPath: /root/.aws
      name: aws-config
      readOnly: true
    - mountPath: /root/.config/gcloud
      name: gcp-config
    - mountPath: /root/gcp-cred.json
      name: gcp-credentials
      subPath: gcp-cred.json
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-852h5
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - |
      echo "Setting up AWS credentials..."
      if [ -n "$AWS_ACCESS_KEY_ID" ] && [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
        echo "AWS credentials found in environment variables."
        aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
        aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
        echo "Credentials file created successfully."
      else
        echo "AWS credentials not found in environment variables. Skipping credentials setup."
        sleep 600
      fi
    command:
    - /bin/sh
    - -c
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          key: aws_access_key_id
          name: aws-credentials
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: aws_secret_access_key
          name: aws-credentials
    image: berkeleyskypilot/skypilot-api-test:20250917043353
    imagePullPolicy: IfNotPresent
    name: create-aws-credentials
    resources: {}
    securityContext:
      capabilities:
        add:
        - ALL
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /root/.aws
      name: aws-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-852h5
      readOnly: true
  - args:
    - |
      gcloud auth activate-service-account --key-file=/root/gcp-cred.json
      gcloud config set project sky-dev-465
    command:
    - /bin/sh
    - -c
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /root/gcp-cred.json
    image: google/cloud-sdk:latest
    imagePullPolicy: Always
    name: setup-gcp-credentials
    resources: {}
    securityContext:
      capabilities:
        add:
        - ALL
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /root/gcp-cred.json
      name: gcp-credentials
      subPath: gcp-cred.json
    - mountPath: /root/.config/gcloud
      name: gcp-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-852h5
      readOnly: true
  nodeName: gke-skypilotalpha-largecpu-05dae726-1usy
  preemptionPolicy: PreemptLowerPriority
  priority: 100
  priorityClassName: low-priority
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: skypilot-alpha-api-sa
  serviceAccountName: skypilot-alpha-api-sa
  terminationGracePeriodSeconds: 60
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: state-volume
  - emptyDir: {}
    name: aws-config
  - name: gcp-credentials
    secret:
      defaultMode: 420
      secretName: gcp-credentials
  - emptyDir: {}
    name: gcp-config
  - configMap:
      defaultMode: 420
      name: skypilot-alpha-config
    name: skypilot-config
  - name: kube-api-access-852h5
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-09-17T05:29:05Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-09-17T05:29:11Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-09-17T05:29:04Z"
    message: 'containers with unready status: [skypilot-api]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-09-17T05:29:04Z"
    message: 'containers with unready status: [skypilot-api]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-09-17T05:29:04Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://c03eeb79385ef57d6a21ca12adc97d6d860d30857af71f4a2d57c47ed484f5f0
    image: docker.io/berkeleyskypilot/skypilot-api-test:20250917043353
    imageID: docker.io/berkeleyskypilot/skypilot-api-test@sha256:9fcd9fbb13a91763af7cbe5da0cfa87116e1ee74604fdcc1d9446b65f6349196
    lastState: {}
    name: skypilot-api
    ready: false
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-09-17T05:29:11Z"
    volumeMounts:
    - mountPath: /var/skypilot/config
      name: skypilot-config
    - mountPath: /root/.aws
      name: aws-config
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /root/.config/gcloud
      name: gcp-config
    - mountPath: /root/gcp-cred.json
      name: gcp-credentials
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-852h5
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.128.0.45
  hostIPs:
  - ip: 10.128.0.45
  initContainerStatuses:
  - containerID: containerd://a765c9d57c167d57cab2ef73bd8f538b580ea956e713fa4e528eca4116ace194
    image: docker.io/berkeleyskypilot/skypilot-api-test:20250917043353
    imageID: docker.io/berkeleyskypilot/skypilot-api-test@sha256:9fcd9fbb13a91763af7cbe5da0cfa87116e1ee74604fdcc1d9446b65f6349196
    lastState: {}
    name: create-aws-credentials
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://a765c9d57c167d57cab2ef73bd8f538b580ea956e713fa4e528eca4116ace194
        exitCode: 0
        finishedAt: "2025-09-17T05:29:07Z"
        reason: Completed
        startedAt: "2025-09-17T05:29:05Z"
    volumeMounts:
    - mountPath: /root/.aws
      name: aws-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-852h5
      readOnly: true
      recursiveReadOnly: Disabled
  - containerID: containerd://3075678fa99e199a0957c93af2ab5bd0039472169a9b9d57347808342f6c3389
    image: docker.io/google/cloud-sdk:latest
    imageID: docker.io/google/cloud-sdk@sha256:8c7cd4e0c76f7802a10b15b09c722622759bc2d5a029a98e6ea494caffcf6956
    lastState: {}
    name: setup-gcp-credentials
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://3075678fa99e199a0957c93af2ab5bd0039472169a9b9d57347808342f6c3389
        exitCode: 0
        finishedAt: "2025-09-17T05:29:10Z"
        reason: Completed
        startedAt: "2025-09-17T05:29:08Z"
    volumeMounts:
    - mountPath: /root/gcp-cred.json
      name: gcp-credentials
    - mountPath: /root/.config/gcloud
      name: gcp-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-852h5
      readOnly: true
      recursiveReadOnly: Disabled
  phase: Running
  podIP: 10.4.2.60
  podIPs:
  - ip: 10.4.2.60
  qosClass: Burstable
  startTime: "2025-09-17T05:29:04Z"
