# Use the latest version with Python 3.10
FROM continuumio/miniconda3:23.3.1-0

# Detect architecture
ARG TARGETARCH

# Install Google Cloud SDK (least likely to change)
RUN conda install -c conda-forge google-cloud-sdk

# Install GKE auth plugin
RUN gcloud components install gke-gcloud-auth-plugin --quiet && \
    find /opt/conda -name 'gke-gcloud-auth-plugin' -type f -exec ln -s {} /usr/local/bin/gke-gcloud-auth-plugin \;

# Install system packages
RUN apt-get update -y && \
    apt-get install --no-install-recommends -y \
        git gcc rsync sudo patch openssh-server \
        pciutils nano fuse socat netcat-openbsd curl rsync vim tini autossh nodejs npm jq && \
    rm -rf /var/lib/apt/lists/*

# Install kubectl based on architecture
RUN ARCH=${TARGETARCH:-$(case "$(uname -m)" in \
        "x86_64") echo "amd64" ;; \
        "aarch64") echo "arm64" ;; \
        *) echo "$(uname -m)" ;; \
    esac)} && \
    curl -LO "https://dl.k8s.io/release/v1.31.6/bin/linux/$ARCH/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm kubectl

# Install NPM and Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g npm@latest

COPY . /skypilot

# Install uv and skypilot
RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
    cd /skypilot && \
    ~/.local/bin/uv pip install --prerelease allow azure-cli --system && \
    ~/.local/bin/uv pip install -e .[all] --system && \
    npm --prefix sky/dashboard install && npm --prefix sky/dashboard run build && \
    # Cleanup all caches to reduce the image size
    conda clean -afy && \
    ~/.local/bin/uv cache clean && \
    rm -rf ~/.cache/pip ~/.cache/uv