# A swiss-knife style dockerfile with some useful tools for SkyPilot nightly
# Automatically installs the nightly version of SkyPilot
#
# Built specifically for amd64 (and not arm64) to allow for  on a Mac.
#
# Build with:
# docker buildx build --load --platform linux/amd64 -t berkeleyskypilot/skypilot-nightly -f Dockerfile_nightly .
#
# Push with:
# docker buildx build --push --platform linux/amd64 -t berkeleyskypilot/skypilot-nightly -f Dockerfile_nightly .
#
# Run with:
# docker run -it --rm --name skypilot-debug berkeleyskypilot/skypilot-nightly /bin/bash

FROM continuumio/miniconda3:23.5.2-0

# Install dependencies
RUN conda install -c conda-forge google-cloud-sdk && \
    apt update -y && \
    apt install rsync vim less curl wget -y && \
    rm -rf /var/lib/apt/lists/*

# Install SkyPilot nightly build when the container is run (not when it's built)
ENTRYPOINT ["/bin/bash", "-c", "pip install 'skypilot-nightly[all]' && /bin/bash"]

CMD ["/bin/bash"]
