apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ssh-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP  # Use clusterIP to allow ingress to authenticate
  ports:
    - port: 80
      name: http
      targetPort: 46582  # Assuming your container listens on port 46582
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-ssh
    skypilot.co/ready: "true"
