"""OCI Offerings Catalog.

This module loads the service catalog file and can be used to query
instance types and pricing information for OCI.

History:
 - Hysun He (hysun.he@oracle.com) @ Apr, 2023: Initial implementation
 - Hysun He (hysun.he@oracle.com) @ Jun, 2023: Reduce retry times by
   excluding those unsubscribed regions.
 - Hysun He (hysun.he@oracle.com) @ Oct 14, 2024: Bug fix for validation
   of the Marketplace images
 - Federico Kamelhar (federico.kamelhar@oracle.com) @ Sep 18, 2026: Pull the
   catalog periodically now that it is generated by
   sky/catalog/data_fetchers/fetch_oci.py.
"""

import logging
import os
import threading
import typing
from typing import Dict, List, Optional, Tuple, Union

from sky.adaptors import oci as oci_adaptor
from sky.catalog import common
from sky.clouds import OCI
from sky.clouds.utils import oci_utils
from sky.utils import resources_utils

if typing.TYPE_CHECKING:
    import pandas as pd

    from sky.clouds import cloud  # pylint: disable=ungrouped-imports

logger = logging.getLogger(__name__)

# Keep in sync with the update-oci-catalog GitHub Action in skypilot-catalog.
_PULL_FREQUENCY_HOURS = 7

_VMS_FILE = 'oci/vms.csv'

# The catalog as published. read_catalog() re-downloads the file every
# _PULL_FREQUENCY_HOURS and reloads this frame on the next access, so keep
# the LazyDataFrame itself and never cache a materialized copy of it.
_vms_df = common.read_catalog(_VMS_FILE,
                              pull_frequency_hours=_PULL_FREQUENCY_HOURS)
_image_df = common.read_catalog('oci/images.csv',
                                pull_frequency_hours=_PULL_FREQUENCY_HOURS)

# The view served to callers: _vms_df restricted to the regions the tenancy
# is subscribed to (or _vms_df itself when that cannot be determined). It is
# rebuilt whenever the catalog file on disk changes, which is detected via
# the file's mtime (the same signal read_catalog() uses to decide staleness).
_df: Optional[Union['pd.DataFrame', common.LazyDataFrame]] = None
_df_catalog_mtime: Optional[float] = None
_subscribed_regions: Optional[List[str]] = None

_lock = threading.RLock()


def _catalog_mtime() -> Optional[float]:
    try:
        return os.path.getmtime(common.get_catalog_path(_VMS_FILE))
    except OSError:
        return None


def _fetch_subscribed_regions() -> List[str]:
    """Returns the regions the configured tenancy is subscribed to.

    Returns an empty list when the OCI SDK or credentials are missing, or the
    call fails, in which case the catalog is served unfiltered.
    """
    try:
        oci_adaptor.oci.load_module()
    except ImportError:
        return []

    try:
        config_profile = oci_utils.oci_config.get_profile()
        client = oci_adaptor.get_identity_client(profile=config_profile)

        subscriptions = client.list_region_subscriptions(
            tenancy_id=oci_adaptor.get_oci_config(
                profile=config_profile)['tenancy']).data

        return [r.region_name for r in subscriptions]

    except (oci_adaptor.oci.exceptions.ConfigFileNotFound,
            oci_adaptor.oci.exceptions.InvalidConfig) as e:
        # This should only happen in testing where oci config is
        # missing, because it means the 'sky check' will fail if
        # enter here (meaning OCI disabled).
        logger.debug(f'It is OK goes here when testing: {str(e)}')
        return []

    except oci_adaptor.oci.exceptions.ServiceError as e:
        # Should never expect going here. However, we still catch
        # it so that if any OCI call failed, the program can still
        # proceed with try-and-error way.
        logger.warning(f'Unexpected exception when handle catalog: {str(e)}')
        return []


def _get_df() -> Union['pd.DataFrame', common.LazyDataFrame]:
    global _df, _df_catalog_mtime, _subscribed_regions
    with _lock:
        # Read through the lazy frame first: this is what gives
        # read_catalog() the chance to replace the file on disk with a fresh
        # copy. Only then is the mtime a faithful generation signal.
        regions = _vms_df['Region']
        mtime = _catalog_mtime()
        if _df is not None and mtime == _df_catalog_mtime:
            return _df

        # The catalog changed (or this is the first call): re-derive the
        # filtered view. The subscribed-region lookup is an OCI API call, so
        # it is only repeated when the catalog actually changed, i.e. at most
        # once per pull.
        _subscribed_regions = _fetch_subscribed_regions()
        if _subscribed_regions:
            _df = _vms_df[regions.isin(_subscribed_regions)]
        else:
            _df = _vms_df
        _df_catalog_mtime = mtime
        return _df


def instance_type_exists(instance_type: str) -> bool:
    return common.instance_type_exists_impl(_get_df(), instance_type)


def validate_region_zone(
        region: Optional[str],
        zone: Optional[str]) -> Tuple[Optional[str], Optional[str]]:
    return common.validate_region_zone_impl('oci', _get_df(), region, zone)


def get_hourly_cost(instance_type: str,
                    use_spot: bool = False,
                    region: Optional[str] = None,
                    zone: Optional[str] = None) -> float:
    """Returns the cost, or the cheapest cost among all zones for spot."""
    return common.get_hourly_cost_impl(_get_df(), instance_type, use_spot,
                                       region, zone)


def get_default_instance_type(
        cpus: Optional[str] = None,
        memory: Optional[str] = None,
        disk_tier: Optional[resources_utils.DiskTier] = None,
        local_disk: Optional[str] = None,
        region: Optional[str] = None,
        zone: Optional[str] = None,
        use_spot: bool = False,
        max_hourly_cost: Optional[float] = None) -> Optional[str]:
    del local_disk  # unused
    if cpus is None:
        cpus = f'{oci_utils.oci_config.DEFAULT_NUM_VCPUS}+'

    if memory is None:
        memory_gb_or_ratio = f'{oci_utils.oci_config.DEFAULT_MEMORY_CPU_RATIO}x'
    else:
        memory_gb_or_ratio = memory

    def _filter_disk_type(instance_type: str) -> bool:
        valid, _ = OCI.check_disk_tier(instance_type, disk_tier)
        return valid

    instance_type_prefix = tuple(
        f'{family}' for family in oci_utils.oci_config.DEFAULT_INSTANCE_FAMILY)

    df = _get_df()
    df = df[df['InstanceType'].notna()]
    df = df[df['InstanceType'].str.startswith(instance_type_prefix)]
    df = df.loc[df['InstanceType'].apply(_filter_disk_type)]

    logger.debug(f'# get_default_instance_type: {df}')
    return common.get_instance_type_for_cpus_mem_impl(df, cpus,
                                                      memory_gb_or_ratio,
                                                      region, zone, use_spot,
                                                      max_hourly_cost)


def get_accelerators_from_instance_type(
        instance_type: str) -> Optional[Dict[str, Union[int, float]]]:
    return common.get_accelerators_from_instance_type_impl(
        _get_df(), instance_type)


def get_instance_type_for_accelerator(
    acc_name: str,
    acc_count: int,
    cpus: Optional[str] = None,
    memory: Optional[str] = None,
    use_spot: bool = False,
    local_disk: Optional[str] = None,
    region: Optional[str] = None,
    zone: Optional[str] = None,
    max_hourly_cost: Optional[float] = None,
) -> Tuple[Optional[List[str]], List[str]]:
    """Filter the instance types based on resource requirements.

    Returns a list of instance types satisfying the required count of
    accelerators with sorted prices and a list of candidates with fuzzy search.
    """
    del local_disk  # unused
    return common.get_instance_type_for_accelerator_impl(
        df=_get_df(),
        acc_name=acc_name,
        acc_count=acc_count,
        cpus=cpus,
        memory=memory,
        use_spot=use_spot,
        region=region,
        zone=zone,
        max_hourly_cost=max_hourly_cost)


def get_region_zones_for_instance_type(instance_type: str,
                                       use_spot: bool) -> List['cloud.Region']:
    df = _get_df()
    df = df[df['InstanceType'] == instance_type]
    return common.get_region_zones(df, use_spot)


def list_accelerators(
        gpus_only: bool,
        name_filter: Optional[str],
        region_filter: Optional[str],
        quantity_filter: Optional[int],
        case_sensitive: bool = True,
        all_regions: bool = False,
        require_price: bool = True) -> Dict[str, List[common.InstanceTypeInfo]]:
    """Returns all instance types in OCI offering GPUs."""
    del require_price  # Unused.
    return common.list_accelerators_impl('OCI', _get_df(), gpus_only,
                                         name_filter, region_filter,
                                         quantity_filter, case_sensitive,
                                         all_regions)


def get_vcpus_mem_from_instance_type(
        instance_type: str) -> Tuple[Optional[float], Optional[float]]:
    return common.get_vcpus_mem_from_instance_type_impl(_get_df(),
                                                        instance_type)


def get_image_id_from_tag(tag: str, region: Optional[str]) -> Optional[str]:
    """Returns the image id from the tag, or None if `region` has none.

    Platform images are catalogued per region, so a region the shape catalog
    knows but the image catalog does not has no image for the tag; Marketplace
    images are catalogued once, without a region, and serve every region.
    """
    df = _image_df[_image_df['Tag'].str.fullmatch(tag)]
    if df.empty:
        return None
    # Always try get region-specific imageid first (for backward compatible)
    image_str = common.get_image_id_from_tag_impl(df, tag, region)
    if image_str is None:
        # Support cross-region (general) imageid
        image_str = common.get_image_id_from_tag_impl(df[df['Region'].isna()],
                                                      tag, None)
    if image_str is None:
        return None

    app_catalog_listing_id = df['AppCatalogListingId'].iloc[0]
    resource_version = df['ResourceVersion'].iloc[0]

    return (f'{image_str}{oci_utils.oci_config.IMAGE_TAG_SPERATOR}'
            f'{app_catalog_listing_id}{oci_utils.oci_config.IMAGE_TAG_SPERATOR}'
            f'{resource_version}')


def is_image_tag_valid(tag: str, region: Optional[str]) -> bool:
    """Returns whether the image tag is valid."""
    # Oct.14, 2024 by Hysun He: Marketplace images are region neutral, so don't
    # check with region for the Marketplace images.
    df = _image_df[_image_df['Tag'].str.fullmatch(tag)]
    if df.empty:
        return False
    app_catalog_listing_id = df['AppCatalogListingId'].iloc[0]
    if app_catalog_listing_id:
        return True
    return common.is_image_tag_valid_impl(_image_df, tag, region)


def get_image_os_from_tag(tag: str, region: Optional[str]) -> Optional[str]:
    del region
    df = _image_df[_image_df['Tag'].str.fullmatch(tag)]
    if df.empty:
        os_type = oci_utils.oci_config.get_default_image_os()
    else:
        os_type = df['OS'].iloc[0]

    logger.debug(f'Operation system for the image {tag} is {os_type}')
    return os_type
