version: '3.5'

services:
  tabby:
    restart: always
    container_name: tabby
    image: tabbyml/tabby
    command: serve --model TabbyML/StarCoder-1B
    volumes:
      - "./tabby:/data"
    ports:
      - 8080:8080
