# Local/On-premise cluster config.
#
# Created by the system administrator to launch a Ray cluster over on-premise machines.
# The system administrator must have `sudo` access to the local nodes.
# Requirements:
#   1) Python (> 3.6) on all nodes.
#   2) Ray CLI (= 2.4.0) on all nodes.
#
# Example usage:
#   >> sky admin deploy cluster-config.yaml

cluster:
  ips: [0.0.0.0, 0.0.0.1]
  name: my-local-cluster 

# Authentication into local cluster nodes.
auth:
  ssh_user: ubuntu
  ssh_private_key: ~/.ssh/ubuntu.pem
