steps:
  - label: "test_minimal"
    command: "pytest tests/smoke_tests/test_basic.py::test_minimal"
    env:
      LOG_TO_STDOUT: "1"

  - label: "test_launch_fast"
    command: "pytest tests/smoke_tests/test_basic.py::test_launch_fast"
    env:
      LOG_TO_STDOUT: "1"
