name: lightning-fabric-lm

resources:
    cpus: 4+
    accelerators: L4

num_nodes: 2

setup: |
    git clone --depth 1 https://github.com/Lightning-AI/pytorch-lightning.git || true
    # SkyPilot's default image on AWS/GCP has CUDA 11.6 (Azure 11.5).
    uv venv --python 3.10
    source .venv/bin/activate
    uv pip install -r requirements.txt "numpy<2" "torch==1.12.1+cu113" --extra-index-url https://download.pytorch.org/whl/cu113
    uv pip install lightning

run: |
    source .venv/bin/activate
    cd pytorch-lightning/examples/fabric/language_model
    export LOGLEVEL=INFO

    MASTER_ADDR=$(echo "$SKYPILOT_NODE_IPS" | head -n1)
    echo "Starting distributed training, head node: $MASTER_ADDR"

    # Explicit check for fabric
    if ! command -v fabric >/dev/null 2>&1; then
        echo "ERROR: fabric command not found" >&2
        exit 1
    fi

    fabric run \
    --num-nodes $SKYPILOT_NUM_NODES \
    --devices $SKYPILOT_NUM_GPUS_PER_NODE \
    --main-address $MASTER_ADDR \
    --main-port 8008 \
    --node-rank $SKYPILOT_NODE_RANK \
    train.py
