# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .action_response import ActionResponse
    from .active_sessions_result import ActiveSessionsResult
    from .active_shell_sessions_result import ActiveShellSessionsResult
    from .annotations import Annotations
    from .annotations_audience_item import AnnotationsAudienceItem
    from .audio_content import AudioContent
    from .available_tool import AvailableTool
    from .bash_command_status import BashCommandStatus
    from .blob_resource_contents import BlobResourceContents
    from .browser_info_result import BrowserInfoResult
    from .browser_viewport import BrowserViewport
    from .button import Button
    from .call_tool_result import CallToolResult
    from .call_tool_result_content_item import (
        CallToolResultContentItem,
        CallToolResultContentItem_Audio,
        CallToolResultContentItem_Image,
        CallToolResultContentItem_Resource,
        CallToolResultContentItem_ResourceLink,
        CallToolResultContentItem_Text,
    )
    from .click_action import ClickAction
    from .code_execute_response import CodeExecuteResponse
    from .code_info_response import CodeInfoResponse
    from .code_language_info import CodeLanguageInfo
    from .console_record import ConsoleRecord
    from .double_click_action import DoubleClickAction
    from .drag_rel_action import DragRelAction
    from .drag_to_action import DragToAction
    from .embedded_resource import EmbeddedResource
    from .file_content_encoding import FileContentEncoding
    from .file_find_result import FileFindResult
    from .file_info import FileInfo
    from .file_list_result import FileListResult
    from .file_read_result import FileReadResult
    from .file_replace_result import FileReplaceResult
    from .file_search_result import FileSearchResult
    from .file_upload_result import FileUploadResult
    from .file_write_result import FileWriteResult
    from .hotkey_action import HotkeyAction
    from .http_validation_error import HttpValidationError
    from .icon import Icon
    from .image_content import ImageContent
    from .jupyter_create_session_response import JupyterCreateSessionResponse
    from .jupyter_execute_response import JupyterExecuteResponse
    from .jupyter_info_response import JupyterInfoResponse
    from .jupyter_output import JupyterOutput
    from .key_down_action import KeyDownAction
    from .key_up_action import KeyUpAction
    from .language import Language
    from .list_tools_result import ListToolsResult
    from .mouse_down_action import MouseDownAction
    from .mouse_up_action import MouseUpAction
    from .move_rel_action import MoveRelAction
    from .move_to_action import MoveToAction
    from .node_js_execute_response import NodeJsExecuteResponse
    from .node_js_output import NodeJsOutput
    from .node_js_runtime_info import NodeJsRuntimeInfo
    from .press_action import PressAction
    from .resolution import Resolution
    from .resource import Resource
    from .resource_link import ResourceLink
    from .response import Response
    from .response_active_sessions_result import ResponseActiveSessionsResult
    from .response_active_shell_sessions_result import ResponseActiveShellSessionsResult
    from .response_browser_info_result import ResponseBrowserInfoResult
    from .response_call_tool_result import ResponseCallToolResult
    from .response_code_execute_response import ResponseCodeExecuteResponse
    from .response_code_info_response import ResponseCodeInfoResponse
    from .response_file_find_result import ResponseFileFindResult
    from .response_file_list_result import ResponseFileListResult
    from .response_file_read_result import ResponseFileReadResult
    from .response_file_replace_result import ResponseFileReplaceResult
    from .response_file_search_result import ResponseFileSearchResult
    from .response_file_upload_result import ResponseFileUploadResult
    from .response_file_write_result import ResponseFileWriteResult
    from .response_jupyter_create_session_response import ResponseJupyterCreateSessionResponse
    from .response_jupyter_execute_response import ResponseJupyterExecuteResponse
    from .response_jupyter_info_response import ResponseJupyterInfoResponse
    from .response_list_str import ResponseListStr
    from .response_list_tools_result import ResponseListToolsResult
    from .response_node_js_execute_response import ResponseNodeJsExecuteResponse
    from .response_node_js_runtime_info import ResponseNodeJsRuntimeInfo
    from .response_shell_command_result import ResponseShellCommandResult
    from .response_shell_create_session_response import ResponseShellCreateSessionResponse
    from .response_shell_kill_result import ResponseShellKillResult
    from .response_shell_view_result import ResponseShellViewResult
    from .response_shell_wait_result import ResponseShellWaitResult
    from .response_shell_write_result import ResponseShellWriteResult
    from .response_str import ResponseStr
    from .response_str_replace_editor_result import ResponseStrReplaceEditorResult
    from .right_click_action import RightClickAction
    from .runtime_env import RuntimeEnv
    from .sandbox_detail import SandboxDetail
    from .sandbox_response import SandboxResponse
    from .scroll_action import ScrollAction
    from .session_info import SessionInfo
    from .shell_command_result import ShellCommandResult
    from .shell_create_session_response import ShellCreateSessionResponse
    from .shell_kill_result import ShellKillResult
    from .shell_session_info import ShellSessionInfo
    from .shell_view_result import ShellViewResult
    from .shell_wait_result import ShellWaitResult
    from .shell_write_result import ShellWriteResult
    from .str_replace_editor_result import StrReplaceEditorResult
    from .system_env import SystemEnv
    from .text_content import TextContent
    from .text_resource_contents import TextResourceContents
    from .tool import Tool
    from .tool_annotations import ToolAnnotations
    from .tool_category import ToolCategory
    from .tool_spec import ToolSpec
    from .typing_action import TypingAction
    from .validation_error import ValidationError
    from .validation_error_loc_item import ValidationErrorLocItem
    from .wait_action import WaitAction
_dynamic_imports: typing.Dict[str, str] = {
    "ActionResponse": ".action_response",
    "ActiveSessionsResult": ".active_sessions_result",
    "ActiveShellSessionsResult": ".active_shell_sessions_result",
    "Annotations": ".annotations",
    "AnnotationsAudienceItem": ".annotations_audience_item",
    "AudioContent": ".audio_content",
    "AvailableTool": ".available_tool",
    "BashCommandStatus": ".bash_command_status",
    "BlobResourceContents": ".blob_resource_contents",
    "BrowserInfoResult": ".browser_info_result",
    "BrowserViewport": ".browser_viewport",
    "Button": ".button",
    "CallToolResult": ".call_tool_result",
    "CallToolResultContentItem": ".call_tool_result_content_item",
    "CallToolResultContentItem_Audio": ".call_tool_result_content_item",
    "CallToolResultContentItem_Image": ".call_tool_result_content_item",
    "CallToolResultContentItem_Resource": ".call_tool_result_content_item",
    "CallToolResultContentItem_ResourceLink": ".call_tool_result_content_item",
    "CallToolResultContentItem_Text": ".call_tool_result_content_item",
    "ClickAction": ".click_action",
    "CodeExecuteResponse": ".code_execute_response",
    "CodeInfoResponse": ".code_info_response",
    "CodeLanguageInfo": ".code_language_info",
    "ConsoleRecord": ".console_record",
    "DoubleClickAction": ".double_click_action",
    "DragRelAction": ".drag_rel_action",
    "DragToAction": ".drag_to_action",
    "EmbeddedResource": ".embedded_resource",
    "FileContentEncoding": ".file_content_encoding",
    "FileFindResult": ".file_find_result",
    "FileInfo": ".file_info",
    "FileListResult": ".file_list_result",
    "FileReadResult": ".file_read_result",
    "FileReplaceResult": ".file_replace_result",
    "FileSearchResult": ".file_search_result",
    "FileUploadResult": ".file_upload_result",
    "FileWriteResult": ".file_write_result",
    "HotkeyAction": ".hotkey_action",
    "HttpValidationError": ".http_validation_error",
    "Icon": ".icon",
    "ImageContent": ".image_content",
    "JupyterCreateSessionResponse": ".jupyter_create_session_response",
    "JupyterExecuteResponse": ".jupyter_execute_response",
    "JupyterInfoResponse": ".jupyter_info_response",
    "JupyterOutput": ".jupyter_output",
    "KeyDownAction": ".key_down_action",
    "KeyUpAction": ".key_up_action",
    "Language": ".language",
    "ListToolsResult": ".list_tools_result",
    "MouseDownAction": ".mouse_down_action",
    "MouseUpAction": ".mouse_up_action",
    "MoveRelAction": ".move_rel_action",
    "MoveToAction": ".move_to_action",
    "NodeJsExecuteResponse": ".node_js_execute_response",
    "NodeJsOutput": ".node_js_output",
    "NodeJsRuntimeInfo": ".node_js_runtime_info",
    "PressAction": ".press_action",
    "Resolution": ".resolution",
    "Resource": ".resource",
    "ResourceLink": ".resource_link",
    "Response": ".response",
    "ResponseActiveSessionsResult": ".response_active_sessions_result",
    "ResponseActiveShellSessionsResult": ".response_active_shell_sessions_result",
    "ResponseBrowserInfoResult": ".response_browser_info_result",
    "ResponseCallToolResult": ".response_call_tool_result",
    "ResponseCodeExecuteResponse": ".response_code_execute_response",
    "ResponseCodeInfoResponse": ".response_code_info_response",
    "ResponseFileFindResult": ".response_file_find_result",
    "ResponseFileListResult": ".response_file_list_result",
    "ResponseFileReadResult": ".response_file_read_result",
    "ResponseFileReplaceResult": ".response_file_replace_result",
    "ResponseFileSearchResult": ".response_file_search_result",
    "ResponseFileUploadResult": ".response_file_upload_result",
    "ResponseFileWriteResult": ".response_file_write_result",
    "ResponseJupyterCreateSessionResponse": ".response_jupyter_create_session_response",
    "ResponseJupyterExecuteResponse": ".response_jupyter_execute_response",
    "ResponseJupyterInfoResponse": ".response_jupyter_info_response",
    "ResponseListStr": ".response_list_str",
    "ResponseListToolsResult": ".response_list_tools_result",
    "ResponseNodeJsExecuteResponse": ".response_node_js_execute_response",
    "ResponseNodeJsRuntimeInfo": ".response_node_js_runtime_info",
    "ResponseShellCommandResult": ".response_shell_command_result",
    "ResponseShellCreateSessionResponse": ".response_shell_create_session_response",
    "ResponseShellKillResult": ".response_shell_kill_result",
    "ResponseShellViewResult": ".response_shell_view_result",
    "ResponseShellWaitResult": ".response_shell_wait_result",
    "ResponseShellWriteResult": ".response_shell_write_result",
    "ResponseStr": ".response_str",
    "ResponseStrReplaceEditorResult": ".response_str_replace_editor_result",
    "RightClickAction": ".right_click_action",
    "RuntimeEnv": ".runtime_env",
    "SandboxDetail": ".sandbox_detail",
    "SandboxResponse": ".sandbox_response",
    "ScrollAction": ".scroll_action",
    "SessionInfo": ".session_info",
    "ShellCommandResult": ".shell_command_result",
    "ShellCreateSessionResponse": ".shell_create_session_response",
    "ShellKillResult": ".shell_kill_result",
    "ShellSessionInfo": ".shell_session_info",
    "ShellViewResult": ".shell_view_result",
    "ShellWaitResult": ".shell_wait_result",
    "ShellWriteResult": ".shell_write_result",
    "StrReplaceEditorResult": ".str_replace_editor_result",
    "SystemEnv": ".system_env",
    "TextContent": ".text_content",
    "TextResourceContents": ".text_resource_contents",
    "Tool": ".tool",
    "ToolAnnotations": ".tool_annotations",
    "ToolCategory": ".tool_category",
    "ToolSpec": ".tool_spec",
    "TypingAction": ".typing_action",
    "ValidationError": ".validation_error",
    "ValidationErrorLocItem": ".validation_error_loc_item",
    "WaitAction": ".wait_action",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ActionResponse",
    "ActiveSessionsResult",
    "ActiveShellSessionsResult",
    "Annotations",
    "AnnotationsAudienceItem",
    "AudioContent",
    "AvailableTool",
    "BashCommandStatus",
    "BlobResourceContents",
    "BrowserInfoResult",
    "BrowserViewport",
    "Button",
    "CallToolResult",
    "CallToolResultContentItem",
    "CallToolResultContentItem_Audio",
    "CallToolResultContentItem_Image",
    "CallToolResultContentItem_Resource",
    "CallToolResultContentItem_ResourceLink",
    "CallToolResultContentItem_Text",
    "ClickAction",
    "CodeExecuteResponse",
    "CodeInfoResponse",
    "CodeLanguageInfo",
    "ConsoleRecord",
    "DoubleClickAction",
    "DragRelAction",
    "DragToAction",
    "EmbeddedResource",
    "FileContentEncoding",
    "FileFindResult",
    "FileInfo",
    "FileListResult",
    "FileReadResult",
    "FileReplaceResult",
    "FileSearchResult",
    "FileUploadResult",
    "FileWriteResult",
    "HotkeyAction",
    "HttpValidationError",
    "Icon",
    "ImageContent",
    "JupyterCreateSessionResponse",
    "JupyterExecuteResponse",
    "JupyterInfoResponse",
    "JupyterOutput",
    "KeyDownAction",
    "KeyUpAction",
    "Language",
    "ListToolsResult",
    "MouseDownAction",
    "MouseUpAction",
    "MoveRelAction",
    "MoveToAction",
    "NodeJsExecuteResponse",
    "NodeJsOutput",
    "NodeJsRuntimeInfo",
    "PressAction",
    "Resolution",
    "Resource",
    "ResourceLink",
    "Response",
    "ResponseActiveSessionsResult",
    "ResponseActiveShellSessionsResult",
    "ResponseBrowserInfoResult",
    "ResponseCallToolResult",
    "ResponseCodeExecuteResponse",
    "ResponseCodeInfoResponse",
    "ResponseFileFindResult",
    "ResponseFileListResult",
    "ResponseFileReadResult",
    "ResponseFileReplaceResult",
    "ResponseFileSearchResult",
    "ResponseFileUploadResult",
    "ResponseFileWriteResult",
    "ResponseJupyterCreateSessionResponse",
    "ResponseJupyterExecuteResponse",
    "ResponseJupyterInfoResponse",
    "ResponseListStr",
    "ResponseListToolsResult",
    "ResponseNodeJsExecuteResponse",
    "ResponseNodeJsRuntimeInfo",
    "ResponseShellCommandResult",
    "ResponseShellCreateSessionResponse",
    "ResponseShellKillResult",
    "ResponseShellViewResult",
    "ResponseShellWaitResult",
    "ResponseShellWriteResult",
    "ResponseStr",
    "ResponseStrReplaceEditorResult",
    "RightClickAction",
    "RuntimeEnv",
    "SandboxDetail",
    "SandboxResponse",
    "ScrollAction",
    "SessionInfo",
    "ShellCommandResult",
    "ShellCreateSessionResponse",
    "ShellKillResult",
    "ShellSessionInfo",
    "ShellViewResult",
    "ShellWaitResult",
    "ShellWriteResult",
    "StrReplaceEditorResult",
    "SystemEnv",
    "TextContent",
    "TextResourceContents",
    "Tool",
    "ToolAnnotations",
    "ToolCategory",
    "ToolSpec",
    "TypingAction",
    "ValidationError",
    "ValidationErrorLocItem",
    "WaitAction",
]
