# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AvailableTool(UniversalBaseModel):
    """
    Describe an available command-line tool.
    """

    name: str = pydantic.Field()
    """
    Tool’s command / binary name
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Tool’s functionality description
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
