# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .code_language_info import CodeLanguageInfo


class CodeInfoResponse(UniversalBaseModel):
    """
    Unified code information response
    """

    languages: typing.List[CodeLanguageInfo] = pydantic.Field()
    """
    List of supported languages and metadata
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
