# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .runtime_env import RuntimeEnv
from .system_env import SystemEnv
from .tool_category import ToolCategory


class SandboxDetail(UniversalBaseModel):
    """
    system environment info
    """

    system: SystemEnv
    runtime: RuntimeEnv
    utils: typing.List[ToolCategory]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
