apiVersion: v2
name: skypilot-platform
description: A Helm chart for deploying SkyPilot platform
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: ingress-nginx
    version: 4.11.3
    repository: https://kubernetes.github.io/ingress-nginx
