/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/X5tLGA3WPNU
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import React, { useState, useEffect, useRef } from 'react';
import { useRouter } from 'next/router';
import Link from 'next/link';
import {
  CircleIcon,
  FilledCircleIcon,
  SquareIcon,
  TickIcon,
} from '@/components/elements/icons';
import { CircularProgress } from '@mui/material';
import { Button } from '@/components/ui/button';

import { Card } from '@/components/ui/card';
import {
  Table,
  TableHeader,
  TableRow,
  TableHead,
  TableBody,
  TableCell,
} from '@/components/ui/table';
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from '@/components/ui/select';
import { getManagedJobs } from '@/data/connectors/jobs';
import { Layout } from '@/components/elements/layout';
import { EventTable } from '@/components/elements/events';
import { CustomTooltip as Tooltip, relativeTime } from '@/components/utils';
import {
  FileSearchIcon,
  RotateCwIcon,
  MonitorPlay,
  Filter,
  PowerIcon,
} from 'lucide-react';
import { streamClusterJobLogs } from '@/data/connectors/clusters';
import { handleJobAction } from '@/data/connectors/jobs';
import { ConfirmationModal } from '@/components/elements/modals';

// Format duration from seconds to a readable format
export function formatDuration(durationInSeconds) {
  if (!durationInSeconds && durationInSeconds !== 0) return '-';

  // Convert to a whole number if it's a float
  durationInSeconds = Math.floor(durationInSeconds);

  if (durationInSeconds < 60) {
    return `${durationInSeconds}s`;
  }

  const hours = Math.floor(durationInSeconds / 3600);
  const minutes = Math.floor((durationInSeconds % 3600) / 60);
  const seconds = durationInSeconds % 60;

  let result = '';
  if (hours > 0) {
    result += `${hours}h `;
  }
  if (minutes > 0 || hours > 0) {
    result += `${minutes}m `;
  }
  if (hours < 1) {
    result += `${seconds}s`;
  }

  return result.trim();
}

export function ManagedJobs() {
  const [activeTab, setActiveTab] = useState('active');
  const [loading, setLoading] = useState(false);
  const refreshDataRef = React.useRef(null);
  const [confirmationModal, setConfirmationModal] = useState({
    isOpen: false,
    title: '',
    message: '',
    onConfirm: null,
  });

  const handleRefresh = () => {
    if (refreshDataRef.current) {
      refreshDataRef.current();
    }
  };

  const handleRestartController = () => {
    setConfirmationModal({
      isOpen: true,
      title: 'Restart Controller',
      message: `Are you sure you want to restart the job controller?`,
      onConfirm: async () => {
        try {
          await handleJobAction('restartcontroller', null, null, true);
          // Only refresh after handleJobAction succeeds
          if (refreshDataRef.current) {
            refreshDataRef.current();
          }
        } finally {
          setConfirmationModal({ ...confirmationModal, isOpen: false });
        }
      },
    });
  };

  return (
    <Layout highlighted="jobs">
      <div className="text-sm mb-4">
        <Link href="/jobs" className="text-sky-blue hover:underline">
          Managed Jobs
        </Link>
      </div>
      <div className="border-b border-gray-200 my-4"></div>
      <div className="flex mb-4">
        <button
          className={`p-2 mx-4 ${activeTab === 'active' ? 'text-sky-blue font-semibold border-b-2 border-sky-blue' : 'text-gray-700'}`}
          onClick={() => setActiveTab('active')}
        >
          Active
        </button>
        <button
          className={`p-2 mx-4 ${activeTab === 'finished' ? 'text-sky-blue font-semibold border-b-2 border-sky-blue' : 'text-gray-700'}`}
          onClick={() => setActiveTab('finished')}
        >
          Finished
        </button>
        <div className="ml-auto flex items-center">
          {loading && (
            <div className="flex items-center mr-2">
              <CircularProgress size={15} className="mt-0" />
              <span className="ml-2 text-gray-500">Loading...</span>
            </div>
          )}
          <Button
            variant="ghost"
            size="icon"
            onClick={handleRefresh}
            disabled={loading}
            className="text-sky-blue hover:text-sky-blue-bright mr-2"
            title="Refresh"
          >
            <RotateCwIcon className="h-5 w-5" />
          </Button>
          <Button
            variant="ghost"
            size="icon"
            onClick={handleRestartController}
            disabled={loading}
            className="text-sky-blue hover:text-sky-blue-bright"
            title="Restart Controller"
          >
            <PowerIcon className="h-5 w-5" />
          </Button>
        </div>
      </div>
      <ManagedJobsTable
        activeTab={activeTab}
        refreshInterval={20000}
        setLoading={setLoading}
        refreshDataRef={refreshDataRef}
      />
      <ConfirmationModal
        isOpen={confirmationModal.isOpen}
        onClose={() => setConfirmationModal({ ...confirmationModal, isOpen: false })}
        onConfirm={confirmationModal.onConfirm}
        title={confirmationModal.title}
        message={confirmationModal.message}
      />
    </Layout>
  );
}

export function ManagedJobsTable({
  activeTab,
  refreshInterval,
  setLoading,
  refreshDataRef,
}) {
  const [data, setData] = useState([]);
  const [sortConfig, setSortConfig] = useState({
    key: null,
    direction: 'ascending',
  });
  const [loading, setLocalLoading] = useState(false);
  const [isInitialLoad, setIsInitialLoad] = useState(true);
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [expandedRowId, setExpandedRowId] = useState(null);
  const expandedRowRef = useRef(null);
  const [selectedStatus, setSelectedStatus] = useState('All');

  // Add this useEffect
  useEffect(() => {
    setSelectedStatus('All');
  }, [activeTab]);

  // Add click outside handler to collapse expanded row
  useEffect(() => {
    function handleClickOutside(event) {
      // If expanded row exists and click is outside of it
      if (
        expandedRowId &&
        expandedRowRef.current &&
        !expandedRowRef.current.contains(event.target)
      ) {
        setExpandedRowId(null);
      }
    }

    // Add event listener
    document.addEventListener('mousedown', handleClickOutside);

    // Clean up the event listener
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [expandedRowId]);

  const fetchData = React.useCallback(async () => {
    setLoading(true);
    setLocalLoading(true);
    let initialData;
    initialData = await getManagedJobs();
    setData(initialData); // Store raw data without sorting
    setLoading(false); // Stop loading for parent component
    setLocalLoading(false); // Stop loading locally
    setIsInitialLoad(false); // No longer initial load after first data fetch
  }, [setLoading]);

  // Expose fetchData to parent component
  React.useEffect(() => {
    if (refreshDataRef) {
      refreshDataRef.current = fetchData;
    }
  }, [refreshDataRef, fetchData]);

  useEffect(() => {
    setData([]);
    let isCurrent = true;

    fetchData();

    const interval = setInterval(() => {
      if (isCurrent) {
        fetchData();
      }
    }, refreshInterval);

    return () => {
      isCurrent = false;
      clearInterval(interval);
    };
  }, [activeTab, refreshInterval, fetchData]);

  // Sort the data if sortConfig is present
  const sortedData = React.useMemo(() => {
    if (!sortConfig.key) return data;

    return [...data].sort((a, b) => {
      if (a[sortConfig.key] < b[sortConfig.key]) {
        return sortConfig.direction === 'ascending' ? -1 : 1;
      }
      if (a[sortConfig.key] > b[sortConfig.key]) {
        return sortConfig.direction === 'ascending' ? 1 : -1;
      }
      return 0;
    });
  }, [data, sortConfig]);

  // Reset to first page when activeTab changes or when data changes
  useEffect(() => {
    setCurrentPage(1);
  }, [activeTab, data.length]);

  const requestSort = (key) => {
    let direction = 'ascending';
    if (sortConfig.key === key && sortConfig.direction === 'ascending') {
      direction = 'descending';
    }
    setSortConfig({ key, direction });
  };

  const getSortDirection = (key) => {
    if (sortConfig.key === key) {
      return sortConfig.direction === 'ascending' ? ' ↑' : ' ↓';
    }
    return '';
  };

  // First, keep the activeTab filter
  const filteredData = sortedData
    .filter((item) => {
      if (activeTab === 'active') {
        return [
          'RUNNING',
          'RECOVERING',
          'PENDING',
          'SUBMITTED',
          'STARTING',
          'CANCELLING',
        ].includes(item.status);
      } else {
        return [
          'SUCCEEDED',
          'FAILED',
          'CANCELLED',
          'FAILED_SETUP',
          'FAILED_PRECHECKS',
          'FAILED_NO_RESOURCE',
          'FAILED_CONTROLLER',
        ].includes(item.status);
      }
    });

  // Calculate status counts from the filtered data
  const statusCounts = React.useMemo(() => {
    const counts = {
      All: filteredData.length,
    };
    filteredData.forEach(item => {
      counts[item.status] = (counts[item.status] || 0) + 1;
    });
    return counts;
  }, [filteredData]);

  // Apply status filter
  const statusFilteredData = React.useMemo(() => {
    if (selectedStatus === 'All') return filteredData;
    return filteredData.filter(item => item.status === selectedStatus);
  }, [filteredData, selectedStatus]);

  // Calculate pagination
  const totalPages = Math.ceil(statusFilteredData.length / pageSize);
  const startIndex = (currentPage - 1) * pageSize;
  const endIndex = startIndex + pageSize;

  // Page navigation handlers
  const goToPreviousPage = () => {
    setCurrentPage((page) => Math.max(page - 1, 1));
  };

  const goToNextPage = () => {
    setCurrentPage((page) => Math.min(page + 1, totalPages));
  };

  const handlePageSizeChange = (e) => {
    const newSize = parseInt(e.target.value, 10);
    setPageSize(newSize);
    setCurrentPage(1); // Reset to first page when changing page size
  };

  const paginatedData = statusFilteredData.slice(startIndex, endIndex);

  return (
    <div className="relative">
      {/* Status Filter Bar */}
      <div className="flex items-center mb-4 text-sm">
        <span className="mr-2 text-gray-600">Filter by status:</span>
        <div className="flex space-x-2">
          <button
            onClick={() => setSelectedStatus('All')}
            className={`px-3 py-1 rounded-full flex items-center space-x-2 ${
              selectedStatus === 'All'
                ? 'bg-gray-100 text-gray-800'
                : 'text-gray-600 hover:bg-gray-50'
            }`}
          >
            <span>ALL</span>
            <span className="text-xs bg-gray-200 px-1.5 py-0.5 rounded">
              {statusCounts.All}
            </span>
          </button>
          {Object.entries(statusCounts)
            .filter(([status]) => status !== 'All')
            .map(([status, count]) => (
              <button
                key={status}
                onClick={() => setSelectedStatus(status)}
                className={`px-3 py-1 rounded-full flex items-center space-x-2 ${
                  selectedStatus === status
                    ? getStatusStyle(status)
                    : 'text-gray-600 hover:bg-gray-50'
                }`}
              >
                <span>{status}</span>
                <span className="text-xs bg-white/50 px-1.5 py-0.5 rounded">
                  {count}
                </span>
              </button>
            ))}
        </div>
      </div>

      <Card>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead
                className="sortable whitespace-nowrap"
                onClick={() => requestSort('id')}
              >
                ID{getSortDirection('id')}
              </TableHead>
              <TableHead
                className="sortable whitespace-nowrap"
                onClick={() => requestSort('name')}
              >
                Name{getSortDirection('name')}
              </TableHead>
              <TableHead
                className="sortable whitespace-nowrap"
                onClick={() => requestSort('submitted_at')}
              >
                Submitted{getSortDirection('submitted_at')}
              </TableHead>
              <TableHead
                className="sortable whitespace-nowrap"
                onClick={() => requestSort('job_duration')}
              >
                Job Duration{getSortDirection('job_duration')}
              </TableHead>
              <TableHead
                className="sortable whitespace-nowrap"
                onClick={() => requestSort('status')}
              >
                Status{getSortDirection('status')}
              </TableHead>
              <TableHead
                className="sortable whitespace-nowrap"
                onClick={() => requestSort('resources')}
              >
                Resources{getSortDirection('resources')}
              </TableHead>
              <TableHead
                className="sortable whitespace-nowrap"
                onClick={() => requestSort('cluster')}
              >
                Cluster{getSortDirection('cluster')}
              </TableHead>
              <TableHead
                className="sortable whitespace-nowrap"
                onClick={() => requestSort('region')}
              >
                Region{getSortDirection('region')}
              </TableHead>
              <TableHead
                className="sortable whitespace-nowrap"
                onClick={() => requestSort('recoveries')}
              >
                Recoveries{getSortDirection('recoveries')}
              </TableHead>
              <TableHead
                className="sortable whitespace-nowrap"
                onClick={() => requestSort('user')}
              >
                User{getSortDirection('user')}
              </TableHead>
              <TableHead>Details</TableHead>
              <TableHead>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {loading && isInitialLoad ? (
              <TableRow>
                <TableCell
                  colSpan={11}
                  className="text-center py-6 text-gray-500"
                >
                  <div className="flex justify-center items-center">
                    <CircularProgress size={20} className="mr-2" />
                    <span>Loading...</span>
                  </div>
                </TableCell>
              </TableRow>
            ) : paginatedData.length > 0 ? (
              paginatedData.map((item, index) => (
                <React.Fragment key={index}>
                  <TableRow
                    className={expandedRowId === item.id ? 'selected-row' : ''}
                  >
                    <TableCell>
                      <Link href={`/jobs/${item.id}`} className="text-blue-600">
                        {item.id}
                      </Link>
                    </TableCell>
                    <TableCell>
                      <Link href={`/jobs/${item.id}`} className="text-blue-600">
                        {item.name}
                      </Link>
                    </TableCell>
                    <TableCell>{relativeTime(item.submitted_at)}</TableCell>
                    <TableCell>{formatDuration(item.job_duration)}</TableCell>
                    <TableCell>
                      <Status2Icon status={item.status} />
                    </TableCell>
                    <TableCell>{item.resources}</TableCell>
                    <TableCell>{item.cluster}</TableCell>
                    <TableCell>{item.region}</TableCell>
                    <TableCell>{item.recoveries}</TableCell>
                    <TableCell>{item.user}</TableCell>
                    <TableCell>
                      {item.details ? (
                        <TruncatedDetails
                          text={item.details}
                          rowId={item.id}
                          expandedRowId={expandedRowId}
                          setExpandedRowId={setExpandedRowId}
                        />
                      ) : (
                        '-'
                      )}
                    </TableCell>
                    <TableCell>
                      <Status2Actions
                        jobParent="/jobs"
                        jobId={item.id}
                        jobName={item.name}
                        status={item.status}
                        managed={true}
                        cluster="job controller"
                      />
                    </TableCell>
                  </TableRow>
                  {expandedRowId === item.id && item.details && (
                    <ExpandedDetailsRow
                      text={item.details}
                      colSpan={11}
                      innerRef={expandedRowRef}
                    />
                  )}
                </React.Fragment>
              ))
            ) : (
              <TableRow>
                <TableCell
                  colSpan={11}
                  className="text-center py-6 text-gray-500"
                >
                  No active jobs
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </Card>

      {/* Pagination controls */}
      {statusFilteredData.length > 0 && (
        <div className="flex justify-end items-center py-2 px-4 text-sm text-gray-700">
          <div className="flex items-center space-x-4">
            <div className="flex items-center">
              <span className="mr-2">Rows per page:</span>
              <div className="relative inline-block">
                <select
                  value={pageSize}
                  onChange={handlePageSizeChange}
                  className="py-1 pl-2 pr-6 appearance-none outline-none cursor-pointer border-none bg-transparent"
                  style={{ minWidth: '40px' }}
                >
                  <option value={10}>10</option>
                  <option value={30}>30</option>
                  <option value={50}>50</option>
                  <option value={100}>100</option>
                  <option value={200}>200</option>
                </select>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-4 w-4 text-gray-500 absolute right-0 top-1/2 transform -translate-y-1/2 pointer-events-none"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M19 9l-7 7-7-7"
                  />
                </svg>
              </div>
            </div>
            <div>
              {startIndex + 1} – {Math.min(endIndex, statusFilteredData.length)} of{' '}
              {statusFilteredData.length}
            </div>
            <div className="flex items-center space-x-2">
              <Button
                variant="ghost"
                size="icon"
                onClick={goToPreviousPage}
                disabled={currentPage === 1}
                className="text-gray-500 h-8 w-8 p-0"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="16"
                  height="16"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  className="chevron-left"
                >
                  <path d="M15 18l-6-6 6-6" />
                </svg>
              </Button>
              <Button
                variant="ghost"
                size="icon"
                onClick={goToNextPage}
                disabled={currentPage === totalPages || totalPages === 0}
                className="text-gray-500 h-8 w-8 p-0"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="16"
                  height="16"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  className="chevron-right"
                >
                  <path d="M9 18l6-6-6-6" />
                </svg>
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// Helper function to get status-specific styling
function getStatusStyle(status) {
  switch (status) {
    case 'RUNNING':
      return 'bg-green-50 text-green-700';
    case 'PENDING':
      return 'bg-yellow-50 text-yellow-700';
    case 'SUCCEEDED':
      return 'bg-blue-50 text-blue-700';
    case 'FAILED':
      return 'bg-red-50 text-red-700';
    case 'CANCELED':
      return 'bg-gray-50 text-gray-700';
    case 'RECOVERING':
      return 'bg-orange-50 text-orange-700';
    case 'SUBMITTED':
      return 'bg-indigo-50 text-indigo-700';
    case 'STARTING':
      return 'bg-cyan-50 text-cyan-700';
    case 'CANCELLING':
      return 'bg-rose-50 text-rose-700';
    default:
      return 'bg-gray-100 text-gray-800';
  }
}

export function JobDetails({
  clusterName,
  jobData,
  parent,
  parentLink,
  withEvents = true,
  highlighted = 'jobs',
  actionButtons,
  customHeader,
  hideTabs = false,
}) {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [activeTab, setActiveTab] = useState('info'); // Default to 'info' tab

  // Update activeTab when the URL query changes
  useEffect(() => {
    if (router.isReady) {
      const tab = router.query.tab || 'info';
      setActiveTab(tab);
    }
  }, [router.isReady, router.query.tab]);

  // Update URL when tab changes
  const handleTabChange = (tab) => {
    if (tab === activeTab) return; // Don't update if it's the same tab

    setActiveTab(tab);

    // Update URL with the selected tab
    router.push(
      {
        pathname: router.pathname,
        query: { ...router.query, tab },
      },
      undefined,
      { shallow: true }
    );
  };

  return (
    <Layout highlighted={highlighted}>
      {customHeader ? (
        // Render custom header if provided
        <>{customHeader}</>
      ) : (
        // Otherwise render default header
        <>
          <div className="flex items-center">
            <div className="text-sm mb-4">
              {parent}
              <span className="mx-2 text-gray-500">›</span>
              <Link
                href={`${parentLink}/${jobData.id}`}
                className="text-sky-blue hover:underline"
              >
                {jobData.job} (ID: {jobData.id})
              </Link>
            </div>
            {(!jobData.job || loading) && (
              <>
                <CircularProgress size={15} className="mx-5 mt-7" />
              </>
            )}
          </div>
          <div className="border-b border-gray-200 my-4"></div>
        </>
      )}

      {!hideTabs && (
        <div className="flex justify-between items-center">
          <div className="flex mb-4">
            <button
              className={`p-2 mx-4 ${activeTab === 'info' ? 'text-blue-600 font-semibold border-b-2 border-blue-600' : 'text-gray-700'}`}
              onClick={() => handleTabChange('info')}
            >
              Info
            </button>
            <button
              className={`p-2 mx-4 ${activeTab === 'logs' ? 'text-blue-600 font-semibold border-b-2 border-blue-600' : 'text-gray-700'}`}
              onClick={() => handleTabChange('logs')}
            >
              Logs
            </button>
            {withEvents && (
              <button
                className={`p-2 mx-4 ${activeTab === 'event' ? 'text-blue-600 font-semibold border-b-2 border-blue-600' : 'text-gray-700'}`}
                onClick={() => handleTabChange('event')}
              >
                Events
              </button>
            )}
          </div>
          {/* Only show action buttons in default header mode */}
          {!customHeader && (
            <div>
              {actionButtons || (
                <Status2Actions
                  jobParent={parentLink}
                  jobId={jobData.id}
                  jobName={jobData.job}
                  status={jobData.status || 'UNKNOWN'}
                  managed={false}
                  cluster={clusterName}
                />
              )}
            </div>
          )}
        </div>
      )}

      <ActiveTab
        clusterName={clusterName}
        jobData={jobData}
        activeTab={activeTab}
        setLoading={setLoading}
      />
    </Layout>
  );
}

export function formatLogs(str) {
  if (!str) return '';

  // First remove ANSI escape codes
  let result = stripAnsiCodes(str);

  // Remove all HTML-like tags while preserving their content
  // This handles both paired tags like <tag>content</tag> and standalone tags like <tag>
  result = result.replace(/<[^>]*>(.*?)<\/[^>]*>/g, '$1'); // Remove paired tags but keep content
  result = result.replace(/<[^>]*>/g, ''); // Remove any remaining standalone tags

  // Remove formatting markers like [dim] and [/dim]
  result = result.replace(/\[([^\]]+)\]/g, ''); // This will remove any text in square brackets

  return result;
}

export function stripAnsiCodes(str) {
  return str.replace(/\x1b\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGKH]/g, '');
}

function extractNodeTypes(logs) {
  const nodePattern = /\((head|worker\d+),/g; // Matches 'head' or 'worker' followed by any number
  const nodeTypes = new Set();

  let match;
  while ((match = nodePattern.exec(logs)) !== null) {
    nodeTypes.add(match[1]); // Add the node type to the set
  }

  const sortedNodeTypes = Array.from(nodeTypes).sort((a, b) => {
    if (a === 'head') return -1;
    if (b === 'head') return 1;
    return a.localeCompare(b, undefined, {
      numeric: true,
      sensitivity: 'base',
    });
  });

  return sortedNodeTypes; // Return sorted array
}

export function LogFilter({ logs }) {
  const [selectedNode, setSelectedNode] = useState('all');
  const [filteredLogs, setFilteredLogs] = useState(logs);
  const [nodeTypes, setNodeTypes] = useState([]);

  useEffect(() => {
    setNodeTypes(extractNodeTypes(logs));
  }, [logs]);

  useEffect(() => {
    if (selectedNode === 'all') {
      setFilteredLogs(logs);
    } else {
      const filtered = logs
        .split('\n')
        .filter((line) => line.includes(`(${selectedNode},`));
      setFilteredLogs(filtered.join('\n'));
    }
  }, [selectedNode, logs]);

  return (
    <div>
      <Select
        onValueChange={(value) => setSelectedNode(value)}
        value={selectedNode}
      >
        <SelectTrigger aria-label="Node">
          <SelectValue placeholder="Select Node" />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="all">All Nodes</SelectItem>
          {nodeTypes.map((node) => (
            <SelectItem key={node} value={node}>
              {node}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
      <br />
      <pre style={{ whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
        {filteredLogs}
      </pre>
    </div>
  );
}
export const contentStyle = {
  height: '80%',
  overflowY: 'scroll',
  padding: '30px',
  backgroundColor: '#f7f7f7',
};

function ActiveTab({ clusterName, jobData, activeTab, setLoading }) {
  const [logs, setLogs] = useState([]);
  const router = useRouter();
  const isClusterJobPage = router.pathname.includes(
    '/clusters/[cluster]/[job]'
  ); // Check if we're on the clusters job page

  // Clear logs when activeTab changes or when jobData.id changes
  useEffect(() => {
    setLogs([]);
  }, [activeTab, jobData.id]);

  // Only fetch logs when actually viewing the logs tab
  useEffect(() => {
    let active = true;

    if (activeTab === 'logs' && clusterName && jobData.id) {
      setLoading(true);

      streamClusterJobLogs({
        clusterName: clusterName,
        jobId: jobData.id,
        onNewLog: (log) => {
          if (active) {
            const strippedLog = formatLogs(log);
            setLogs((prevLogs) => [...prevLogs, strippedLog]);
          }
        },
      })
        .then(() => {
          if (active) {
            setLoading(false);
          }
        })
        .catch((error) => {
          if (active) {
            console.error('Error streaming logs:', error);
            setLoading(false);
          }
        });
    } else if (activeTab !== 'logs') {
      setLoading(false);
    }

    return () => {
      active = false;
    };
  }, [activeTab, clusterName, jobData.id, setLoading]);

  // For clusters job page with hidden tabs, we want to show different content based on the URL tab parameter
  if (isClusterJobPage) {
    if (activeTab === 'logs') {
      return (
        <div className="items-center mb-6">
          <Card style={contentStyle}>
            <LogFilter logs={logs.join('')} />
          </Card>
        </div>
      );
    }

    // Default to info tab for hidden tabs
    return (
      <div className="items-center mb-6">
        <Card className="p-3">
          <div className="grid grid-cols-2 gap-6">
            <div>
              <div className="text-gray-600 font-medium text-lg">Job ID</div>
              <div className="text-sm mt-1">{jobData.id}</div>
            </div>
            <div>
              <div className="text-gray-600 font-medium text-lg">User</div>
              <div className="text-sm mt-1">{jobData.user}</div>
            </div>
            <div>
              <div className="text-gray-600 font-medium text-lg">Status</div>
              <div className="text-sm mt-1">{jobData.status}</div>
            </div>
            {jobData.resources && (
              <div>
                <div className="text-gray-600 font-medium text-lg">Resources</div>
                <div className="text-sm mt-1">{jobData.resources || 'N/A'}</div>
              </div>
            )}
            <div>
              <div className="text-gray-600 font-medium text-lg">Job Name</div>
              <div className="text-sm mt-1">{jobData.job}</div>
            </div>
            {jobData.cluster && (
              <div>
                <div className="text-gray-600 font-medium text-lg">Cluster</div>
                <div className="text-sm mt-1">
                  <Link
                    href={`/clusters/${jobData.cluster}`}
                    className="text-sky-blue hover:underline"
                  >
                    {jobData.cluster}
                  </Link>
                </div>
              </div>
            )}
            {jobData.infra && (
              <div>
                <div className="text-gray-600 font-medium text-lg">Infra</div>
                <div className="text-sm mt-1">{jobData.infra}</div>
              </div>
            )}
          </div>
        </Card>
      </div>
    );
  }
}

function status2Icon(status) {
  const badgeClasses =
    'inline-flex items-center px-2 py-1 rounded-full text-xs font-medium';
  switch (status) {
    case 'RUNNING':
      return (
        <span className={`${badgeClasses} bg-green-50 text-green-700`}>
          <FilledCircleIcon className="w-2 h-2 mr-2" />
          RUNNING
        </span>
      );
    case 'PENDING':
      return (
        <span className={`${badgeClasses} bg-yellow-50 text-yellow-700`}>
          <CircleIcon className="w-2 h-2 mr-2" />
          PENDING
        </span>
      );
    case 'SUCCEEDED':
      return (
        <span className={`${badgeClasses} bg-blue-50 text-blue-700`}>
          <TickIcon className="w-2 h-2 mr-2" />
          SUCCEEDED
        </span>
      );
    case 'FAILED':
      return (
        <span className={`${badgeClasses} bg-red-50 text-red-700`}>
          <SquareIcon className="w-2 h-2 mr-2" />
          FAILED
        </span>
      );
    case 'CANCELED':
      return (
        <span className={`${badgeClasses} bg-gray-50 text-gray-700`}>
          <SquareIcon className="w-2 h-2 mr-2" />
          CANCELLED
        </span>
      );
    case 'RECOVERING':
      return (
        <span className={`${badgeClasses} bg-orange-50 text-orange-700`}>
          <CircleIcon className="w-2 h-2 mr-2" />
          RECOVERING
        </span>
      );
    case 'SUBMITTED':
      return (
        <span className={`${badgeClasses} bg-indigo-50 text-indigo-700`}>
          <CircleIcon className="w-2 h-2 mr-2" />
          SUBMITTED
        </span>
      );
    case 'STARTING':
      return (
        <span className={`${badgeClasses} bg-cyan-50 text-cyan-700`}>
          <CircleIcon className="w-2 h-2 mr-2" />
          STARTING
        </span>
      );
    case 'CANCELLING':
      return (
        <span className={`${badgeClasses} bg-rose-50 text-rose-700`}>
          <CircleIcon className="w-2 h-2 mr-2" />
          CANCELLING
        </span>
      );
    case 'FAILED_SETUP':
      return (
        <span className={`${badgeClasses} bg-pink-50 text-pink-700`}>
          <CircleIcon className="w-2 h-2 mr-2" />
          FAILED_SETUP
        </span>
      );
    case 'FAILED_PRECHECKS':
      return (
        <span className={`${badgeClasses} bg-red-50 text-red-700`}>
          <CircleIcon className="w-2 h-2 mr-2" />
          FAILED_PRECHECKS
        </span>
      );
    case 'FAILED_NO_RESOURCE':
      return (
        <span className={`${badgeClasses} bg-red-50 text-red-700`}>
          <CircleIcon className="w-2 h-2 mr-2" />
          FAILED_NO_RESOURCE
        </span>
      );
    case 'FAILED_CONTROLLER':
      return (
        <span className={`${badgeClasses} bg-red-50 text-red-700`}>
          <CircleIcon className="w-2 h-2 mr-2" />
          FAILED_CONTROLLER
        </span>
      );
    default:
      return (
        <span className={`${badgeClasses} bg-gray-100 text-gray-800`}>
          <FilledCircleIcon className="w-3 h-3 mr-1" />
          {status}
        </span>
      );
  }
}

export function Status2Icon({ status }) {
  return (
    <Tooltip content={status} className="text-muted-foreground text-sm">
      <span>{status2Icon(status)}</span>
    </Tooltip>
  );
}

export function Status2Actions({
  withLabel = false,
  jobParent,
  jobId,
  jobName,
  status,
  managed,
  cluster,
}) {
  const router = useRouter();
  const actions = ['logs'];
  if (managed) {
    actions.push('controllerlogs');
  }

  const [confirmationModal, setConfirmationModal] = useState({
    isOpen: false,
    title: '',
    message: '',
    onConfirm: null,
  });

  const handleLogsClick = (e, logType) => {
    e.preventDefault();
  
    // Use Next.js router for navigation if on the same page, otherwise direct URL
    const targetPath = `${jobParent}/${jobId}`;
  
    if (router.pathname.includes(targetPath)) {
      // If we're already on the job page, just change the tab parameter
      router.push(
        {
          pathname: router.pathname,
          query: { ...router.query, tab: logType },
        },
        undefined,
        { shallow: true }
      );
    } else {
      // If we're navigating to a different page, use the full URL
      router.push(`${targetPath}?tab=${logType}`);
    }
  };

  return (
    <>
      <span className="flex content-center items-center text-sm">
        <Tooltip
          key="logs"
          content="View Job Logs"
          className="capitalize text-sm text-muted-foreground"
        >
          <button
            onClick={(e) => handleLogsClick(e, 'logs')}
            className="text-sky-blue hover:text-sky-blue-bright font-medium mx-2 flex items-center"
          >
            <FileSearchIcon className="w-4 h-4 mr-1.5 text-gray-500 inline-block" />
            {withLabel && 'Logs'}
          </button>
        </Tooltip>
        {managed && (
          <Tooltip
            key="controllerlogs"
            content="View Controller Logs"
            className="capitalize text-sm text-muted-foreground"
          >
            <button
              onClick={(e) => handleLogsClick(e, 'controllerlogs')}
              className="text-sky-blue hover:text-sky-blue-bright font-medium mx-2 flex items-center"
            >
              <MonitorPlay className="w-4 h-4 mr-1.5 text-gray-500 inline-block" />
              {withLabel && 'Controller Logs'}
            </button>
          </Tooltip>
        )}
      </span>
    </>
  );
}

export function ClusterJobs({ clusterName, clusterJobData }) {
  const [expandedRowId, setExpandedRowId] = useState(null);
  const [sortConfig, setSortConfig] = useState({
    key: null,
    direction: 'ascending',
  });
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const expandedRowRef = useRef(null);
  const [loading, setLoading] = useState(true);
  const [isInitialLoad, setIsInitialLoad] = useState(true); // Track if it's the initial load
  const [prevClusterJobData, setPrevClusterJobData] = useState(null); // Track previous data

  useEffect(() => {
    const handleClickOutside = (event) => {
      if (
        expandedRowId &&
        expandedRowRef.current &&
        !expandedRowRef.current.contains(event.target)
      ) {
        setExpandedRowId(null);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [expandedRowId]);

  const jobData = React.useMemo(() => {
    return clusterJobData || [];
  }, [clusterJobData]);

  useEffect(() => {
    // Check if the data has changed significantly (new data received)
    if (JSON.stringify(clusterJobData) !== JSON.stringify(prevClusterJobData)) {
      setLoading(true);
      setPrevClusterJobData(clusterJobData);
    }

    // Set loading to false when job data is available
    if (jobData.length > 0) {
      setIsInitialLoad(false); // No longer initial load after first data fetch with content
    }
    setLoading(false);
  }, [clusterJobData, jobData.length, prevClusterJobData]);

  // Sort the data if sortConfig is present
  const sortedData = React.useMemo(() => {
    if (!sortConfig.key) return jobData;

    return [...jobData].sort((a, b) => {
      if (a[sortConfig.key] < b[sortConfig.key]) {
        return sortConfig.direction === 'ascending' ? -1 : 1;
      }
      if (a[sortConfig.key] > b[sortConfig.key]) {
        return sortConfig.direction === 'ascending' ? 1 : -1;
      }
      return 0;
    });
  }, [jobData, sortConfig]);

  const requestSort = (key) => {
    let direction = 'ascending';
    if (sortConfig.key === key && sortConfig.direction === 'ascending') {
      direction = 'descending';
    }
    setSortConfig({ key, direction });
  };

  const getSortDirection = (key) => {
    if (sortConfig.key === key) {
      return sortConfig.direction === 'ascending' ? ' ↑' : ' ↓';
    }
    return '';
  };

  // Calculate pagination
  const totalPages = Math.ceil(sortedData.length / pageSize);
  const startIndex = (currentPage - 1) * pageSize;
  const endIndex = startIndex + pageSize;
  const paginatedData = sortedData.slice(startIndex, endIndex);

  // Page navigation handlers
  const goToPreviousPage = () => {
    setCurrentPage((page) => Math.max(page - 1, 1));
  };

  const goToNextPage = () => {
    setCurrentPage((page) => Math.min(page + 1, totalPages));
  };

  const handlePageSizeChange = (e) => {
    const newSize = parseInt(e.target.value, 10);
    setPageSize(newSize);
    setCurrentPage(1); // Reset to first page when changing page size
  };

  return (
    <div className="relative">
      <Card>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead
                className="sortable whitespace-nowrap"
                onClick={() => requestSort('id')}
              >
                ID{getSortDirection('id')}
              </TableHead>
              <TableHead
                className="sortable whitespace-nowrap"
                onClick={() => requestSort('job')}
              >
                Name{getSortDirection('job')}
              </TableHead>
              <TableHead
                className="sortable whitespace-nowrap"
                onClick={() => requestSort('submitted_at')}
              >
                Submitted{getSortDirection('submitted_at')}
              </TableHead>
              <TableHead
                className="sortable whitespace-nowrap"
                onClick={() => requestSort('job_duration')}
              >
                Job Duration{getSortDirection('job_duration')}
              </TableHead>
              <TableHead
                className="sortable whitespace-nowrap"
                onClick={() => requestSort('status')}
              >
                Status{getSortDirection('status')}
              </TableHead>
              <TableHead
                className="sortable whitespace-nowrap"
                onClick={() => requestSort('resources')}
              >
                Resources{getSortDirection('resources')}
              </TableHead>
              <TableHead
                className="sortable whitespace-nowrap"
                onClick={() => requestSort('user')}
              >
                User{getSortDirection('user')}
              </TableHead>
              <TableHead>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {loading && isInitialLoad ? (
              <TableRow>
                <TableCell
                  colSpan={7}
                  className="text-center py-6 text-gray-500"
                >
                  <div className="flex justify-center items-center">
                    <CircularProgress size={20} className="mr-2" />
                    <span>Loading...</span>
                  </div>
                </TableCell>
              </TableRow>
            ) : paginatedData.length > 0 ? (
              paginatedData.map((item) => (
                <React.Fragment key={item.id}>
                  <TableRow
                    className={expandedRowId === item.id ? 'selected-row' : ''}
                  >
                    <TableCell>
                      <Link
                        href={`/clusters/${clusterName}/${item.id}`}
                        className="text-blue-600"
                      >
                        {item.id}
                      </Link>
                    </TableCell>
                    <TableCell>
                      <Link
                        href={`/clusters/${clusterName}/${item.id}`}
                        className="text-blue-600"
                      >
                        <TruncatedDetails
                          text={item.job || 'Unnamed job'}
                          rowId={item.id}
                          expandedRowId={expandedRowId}
                          setExpandedRowId={setExpandedRowId}
                        />
                      </Link>
                    </TableCell>
                    <TableCell>{relativeTime(item.submitted_at)}</TableCell>
                    <TableCell>{formatDuration(item.job_duration)}</TableCell>
                    <TableCell>
                      <Status2Icon status={item.status} />
                    </TableCell>
                    <TableCell>{item.resources}</TableCell>
                    <TableCell>{item.user}</TableCell>
                    <TableCell className="flex content-center items-center">
                      <Status2Actions
                        jobParent={`/clusters/${clusterName}`}
                        jobId={item.id}
                        jobName={item.job}
                        status={item.status}
                        managed={false}
                        cluster={clusterName}
                      />
                    </TableCell>
                  </TableRow>
                  {expandedRowId === item.id && (
                    <ExpandedDetailsRow
                      text={item.job || 'Unnamed job'}
                      colSpan={7}
                      innerRef={expandedRowRef}
                    />
                  )}
                </React.Fragment>
              ))
            ) : (
              <TableRow>
                <TableCell
                  colSpan={7}
                  className="text-center py-6 text-gray-500"
                >
                  No jobs found
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </Card>

      {/* Show small loading indicator in corner when not initial load */}
      {loading && !isInitialLoad && paginatedData.length > 0 && (
        <div className="fixed bottom-4 right-4 bg-white rounded-full shadow-lg p-3 z-50">
          <CircularProgress size={24} />
        </div>
      )}

      {sortedData.length > 0 && (
        <div className="flex justify-end items-center py-2 px-4 text-sm text-gray-700">
          <div className="flex items-center space-x-4">
            <div className="flex items-center">
              <span className="mr-2">Rows per page:</span>
              <div className="relative inline-block">
                <select
                  value={pageSize}
                  onChange={handlePageSizeChange}
                  className="py-1 pl-2 pr-6 appearance-none outline-none cursor-pointer border-none bg-transparent"
                  style={{ minWidth: '40px' }}
                >
                  <option value={5}>5</option>
                  <option value={10}>10</option>
                  <option value={20}>20</option>
                  <option value={50}>50</option>
                </select>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-4 w-4 text-gray-500 absolute right-0 top-1/2 transform -translate-y-1/2 pointer-events-none"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M19 9l-7 7-7-7"
                  />
                </svg>
              </div>
            </div>
            <div>
              {startIndex + 1} – {Math.min(endIndex, sortedData.length)} of{' '}
              {sortedData.length}
            </div>
            <div className="flex items-center space-x-2">
              <Button
                variant="ghost"
                size="icon"
                onClick={goToPreviousPage}
                disabled={currentPage === 1}
                className="text-gray-500 h-8 w-8 p-0"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="16"
                  height="16"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  className="chevron-left"
                >
                  <path d="M15 18l-6-6 6-6" />
                </svg>
              </Button>
              <Button
                variant="ghost"
                size="icon"
                onClick={goToNextPage}
                disabled={currentPage === totalPages || totalPages === 0}
                className="text-gray-500 h-8 w-8 p-0"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="16"
                  height="16"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  className="chevron-right"
                >
                  <path d="M9 18l6-6-6-6" />
                </svg>
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function ExpandedDetailsRow({ text, colSpan, innerRef }) {
  return (
    <TableRow className="expanded-details">
      <TableCell colSpan={colSpan}>
        <div
          className="p-4 bg-gray-50 rounded-md border border-gray-200"
          ref={innerRef}
        >
          <p className="text-sm font-medium text-gray-900">Full Details</p>
          <p
            className="mt-1 text-sm text-gray-700"
            style={{ whiteSpace: 'pre-wrap' }}
          >
            {text}
          </p>
        </div>
      </TableCell>
    </TableRow>
  );
}

function TruncatedDetails({ text, rowId, expandedRowId, setExpandedRowId }) {
  const isTruncated = text.length > 50;
  const displayText = isTruncated ? `${text.substring(0, 50)}` : text;

  const handleClick = (e) => {
    e.stopPropagation();
    if (isTruncated) {
      setExpandedRowId(expandedRowId === rowId ? null : rowId);
    }
  };

  return (
    <div
      className="truncated-details relative truncate max-w-full"
      onClick={handleClick}
    >
      <span className={`${isTruncated ? 'cursor-pointer' : ''}`}>
        {displayText}
        {isTruncated && (
          <span className="text-blue-600 hover:text-blue-800 font-medium ml-1 whitespace-nowrap">
            ... show more
          </span>
        )}
      </span>
    </div>
  );
}
