# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: server_deployment_test
templates:
  - templates/api-deployment.yaml
tests:
  - it: should mount kubeconfig correctly when useKubeconfig is enabled
    set:
      kubernetesCredentials.useKubeconfig: true
    asserts:
      - contains:
          path: spec.template.spec.containers[0].volumeMounts
          content:
            name: kube-config
            mountPath: /root/.kube
      - contains:
          path: spec.template.spec.volumes
          content:
            name: kube-config
            secret:
              secretName: kube-credentials

  - it: should persist .kube directory when sshNodePool is enabled
    set:
      apiService.sshNodePools: test
    asserts:
      - contains:
          path: spec.template.spec.containers[0].volumeMounts
          content:
            name: state-volume
            mountPath: /root/.kube
            subPath: .kube

  - it: should merge kubeconfig from .kube and configmap when useKubeconfig and sshNodePool are both enabled
    set:
      kubernetesCredentials.useKubeconfig: true
      apiService.sshNodePools: test
    asserts:
      - contains:
          path: spec.template.spec.containers[0].volumeMounts
          content:
            name: kube-config
            mountPath: /var/skypilot/kubeconfig
      - contains:
          path: spec.template.spec.containers[0].volumeMounts
          content:
            name: state-volume
            mountPath: /root/.kube
            subPath: .kube
      - contains:
          path: spec.template.spec.containers[0].env
          content:
            name: KUBECONFIG
            value: /root/.kube/config:/var/skypilot/kubeconfig/config

  - it: should mount r2 credentials correctly when r2Credentials is enabled
    set:
      r2Credentials.enabled: true
      r2Credentials.r2SecretName: my-r2-secret
    asserts:
      - contains:
          path: spec.template.spec.containers[0].volumeMounts
          content:
            name: r2-credentials
            mountPath: /root/.cloudflare
      - contains:
          path: spec.template.spec.volumes
          content:
            name: r2-credentials
            secret:
              secretName: my-r2-secret

  - it: should not mount r2 credentials when r2Credentials is disabled
    set:
      r2Credentials.enabled: false
    asserts:
      - notContains:
          path: spec.template.spec.containers[0].volumeMounts
          content:
            name: r2-credentials
      - notContains:
          path: spec.template.spec.volumes
          content:
            name: r2-credentials

  - it: should use default r2SecretName when not specified
    set:
      r2Credentials.enabled: true
    asserts:
      - contains:
          path: spec.template.spec.volumes
          content:
            name: r2-credentials
            secret:
              secretName: r2-credentials
