# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: server_deployment_test
templates:
  - templates/api-deployment.yaml
tests:
  - it: should mount kubeconfig correctly when useKubeconfig is enabled
    set:
      kubernetesCredentials.useKubeconfig: true
    asserts:
      - contains:
          path: spec.template.spec.containers[0].volumeMounts
          content:
            name: kube-config
            mountPath: /root/.kube
      - contains:
          path: spec.template.spec.volumes
          content:
            name: kube-config
            secret:
              secretName: kube-credentials

  - it: should persist .kube directory when sshNodePool is enabled
    set:
      apiService.sshNodePools: test
    asserts:
      - contains:
          path: spec.template.spec.containers[0].volumeMounts
          content:
            name: state-volume
            mountPath: /root/.kube
            subPath: .kube

  - it: should merge kubeconfig from .kube and configmap when useKubeconfig and sshNodePool are both enabled
    set:
      kubernetesCredentials.useKubeconfig: true
      apiService.sshNodePools: test
    asserts:
      - contains:
          path: spec.template.spec.containers[0].volumeMounts
          content:
            name: kube-config
            mountPath: /var/skypilot/kubeconfig
      - contains:
          path: spec.template.spec.containers[0].volumeMounts
          content:
            name: state-volume
            mountPath: /root/.kube
            subPath: .kube
      - contains:
          path: spec.template.spec.containers[0].env
          content:
            name: KUBECONFIG
            value: /root/.kube/config:/var/skypilot/kubeconfig/config
