GLOBAL_USER_STATE_DB_NAME = 'state_db'
GLOBAL_USER_STATE_VERSION = '001'

SKYPILOT_CONFIG_DB_NAME = 'skypilot_config_db'
SKYPILOT_CONFIG_VERSION = '001'

SPOT_JOBS_DB_NAME = 'spot_jobs_db'
SPOT_JOBS_VERSION = '001'
