"""Daytona API client helpers for the SkyPilot provisioner.

Daytona (https://www.daytona.io) runs sandboxes: isolated cloud
environments with per-second billing. This module wraps the small subset
of the Daytona REST API that SkyPilot needs: creating sandboxes, listing
them by label, deleting them, and issuing SSH access tokens.

Authentication uses an API key from the ``DAYTONA_API_KEY`` environment
variable or the ``~/.daytona/api_key`` file. SSH access to a sandbox uses
short-lived tokens issued per sandbox and consumed as the SSH username
against the ``ssh.app.daytona.io`` gateway; no SSH key registration with
the cloud is required.
"""

import functools
import json
import os
import time
from typing import Any, Dict, List, Optional

import requests

from sky import sky_logging
from sky.utils import status_lib

logger = sky_logging.init_logger(__name__)

DEFAULT_API_URL = 'https://app.daytona.io/api'
ENV_API_KEY = 'DAYTONA_API_KEY'
ENV_API_URL = 'DAYTONA_API_URL'
CREDENTIALS_PATH = '~/.daytona/api_key'

SSH_GATEWAY_HOST = 'ssh.app.daytona.io'
SSH_GATEWAY_PORT = 22
# SSH access tokens double as the SSH username. Issue long-lived tokens so
# that an existing cluster stays reachable between provisioner refreshes.
SSH_TOKEN_EXPIRES_MINUTES = 30 * 24 * 60  # 30 days.

# Label used to associate sandboxes with a SkyPilot cluster.
CLUSTER_LABEL = 'skypilot-cluster'

# Default sandbox image. Sandboxes are created through the dynamic image
# build path (`buildInfo` with a `FROM <image>` Dockerfile): it is the
# create mode that allows custom vCPU/memory/disk resources, which are
# required so that provisioned sandboxes match the catalog's priced
# shapes. Builds are cached per image, so subsequent launches are fast.
DEFAULT_IMAGE = 'daytonaio/sandbox:latest'

_TIMEOUT = 60
_LAUNCH_TIMEOUT = 20 * 60  # GPU sandboxes may wait for capacity.
_POLL_INTERVAL = 5

# Mapping from SkyPilot instance types to Daytona GPU type identifiers
# (the `gpuType` values accepted by the sandbox create API). Instance
# types are generated by sky/catalog/data_fetchers/fetch_daytona.py.
GPU_INSTANCE_TYPE_TO_DAYTONA_GPU = {
    'B300': 'B300',
    'H200': 'H200',
    'H100': 'H100',
    'RTXPRO6000': 'RTX-PRO-6000',
    'RTX5090': 'RTX-5090',
    'RTX4090': 'RTX-4090',
    'MI355X': 'MI355X',
}

# Per-GPU sandbox resources requested for GPU instance types. Daytona
# meters vCPU/memory independently; these are the representative shapes
# used in the catalog, so the provisioned sandbox matches the priced one.
CPUS_PER_GPU = 8
MEMORY_PER_GPU_GIB = 100
CONSUMER_MEMORY_PER_GPU_GIB = 50
CONSUMER_GPUS = ('RTX5090', 'RTX4090')


class DaytonaError(Exception):
    """Raised when a Daytona API call fails."""


def get_credentials_path() -> str:
    return CREDENTIALS_PATH


def get_api_key() -> str:
    """Returns the Daytona API key from the env var or credentials file."""
    api_key = os.environ.get(ENV_API_KEY)
    if api_key:
        return api_key.strip()
    path = os.path.expanduser(CREDENTIALS_PATH)
    if os.path.exists(path):
        with open(path, 'r', encoding='utf-8') as f:
            api_key = f.read().strip()
        if api_key:
            return api_key
    raise DaytonaError(
        f'Daytona API key not found. Set {ENV_API_KEY} or create '
        f'{CREDENTIALS_PATH}.')


def get_api_url() -> str:
    return os.environ.get(ENV_API_URL, DEFAULT_API_URL).rstrip('/')


def _headers() -> Dict[str, str]:
    return {
        'Authorization': f'Bearer {get_api_key()}',
        'Content-Type': 'application/json',
    }


def _request(method: str,
             path: str,
             params: Optional[Dict[str, Any]] = None,
             body: Optional[Dict[str, Any]] = None,
             timeout: int = _TIMEOUT) -> Any:
    url = f'{get_api_url()}{path}'
    try:
        response = requests.request(method,
                                    url,
                                    headers=_headers(),
                                    params=params,
                                    json=body,
                                    timeout=timeout)
    except requests.exceptions.RequestException as e:
        raise DaytonaError(f'Daytona API request failed: {method} '
                           f'{path}: {e}') from e
    if response.status_code >= 400:
        raise DaytonaError(
            f'Daytona API error {response.status_code} on {method} {path}: '
            f'{response.text[:300]}')
    if response.status_code == 204 or not response.content:
        return None
    return response.json()


def to_cluster_status(
        state: Optional[str]) -> Optional['status_lib.ClusterStatus']:
    """Maps a Daytona sandbox state to a SkyPilot cluster status."""
    if state is None:
        return None
    state = state.lower()
    if state in ('started',):
        return status_lib.ClusterStatus.UP
    # Some states (e.g. forking, pausing, paused, resuming) only occur for
    # VM sandboxes, which this provisioner never creates; they are mapped
    # defensively in case they ever appear on a listed sandbox.
    if state in ('creating', 'restoring', 'pulling_snapshot', 'starting',
                 'unknown', 'pending_build', 'building_snapshot', 'resizing',
                 'snapshotting', 'forking', 'resuming'):
        return status_lib.ClusterStatus.INIT
    if state in ('stopped', 'stopping', 'archiving', 'archived', 'pausing',
                 'paused'):
        return status_lib.ClusterStatus.STOPPED
    if state in ('error', 'build_failed'):
        return status_lib.ClusterStatus.INIT
    if state in ('destroyed', 'destroying', 'deleted'):
        return None
    logger.debug(f'Unrecognized Daytona sandbox state: {state}')
    return status_lib.ClusterStatus.INIT


@functools.lru_cache(maxsize=1)
def _get_organization_id() -> str:
    """Resolves the organization ID of the configured API key."""
    data = _request('GET', '/api-keys/current')
    organization_id = data.get('organizationId')
    if not organization_id:
        raise DaytonaError(
            f'API key response is missing organizationId: {data}')
    return organization_id


def check_gpu_capacity(daytona_gpu: str, count: int, use_spot: bool) -> None:
    """Fails fast when the GPU fleet lacks capacity for the request.

    Without this check, a sandbox create for an exhausted GPU type waits
    for capacity to free up; failing fast instead lets SkyPilot fail over
    to other clouds immediately. Errors from the capacity endpoint itself
    are ignored: the create call remains the source of truth.
    """
    tier = 'availableSpot' if use_spot else 'availableOnDemand'
    try:
        organization_id = _get_organization_id()
        data = _request('GET', f'/organizations/{organization_id}/gpu-capacity')
        capacity_rows = data.get('capacity', [])
    except DaytonaError as e:
        logger.debug(f'GPU capacity check skipped: {e}')
        return
    for row in capacity_rows:
        if row.get('gpuType') != daytona_gpu:
            continue
        available = row.get(tier) or 0
        if available >= count:
            return
        raise DaytonaError(
            f'Insufficient Daytona capacity for {count}x {daytona_gpu} '
            f'({("spot" if use_spot else "on-demand")}): {available} '
            'GPU(s) currently available.')
    raise DaytonaError(
        f'GPU type {daytona_gpu} has no capacity in the Daytona fleet.')


def list_cluster_sandboxes(cluster_name_on_cloud: str) -> List[Dict[str, Any]]:
    """Lists sandboxes labeled with the given SkyPilot cluster name.

    Follows the list endpoint's cursor-based pagination until exhausted.
    """
    labels = json.dumps({CLUSTER_LABEL: cluster_name_on_cloud})
    sandboxes = []
    cursor: Optional[str] = None
    while True:
        params: Dict[str, Any] = {'labels': labels}
        if cursor is not None:
            params['cursor'] = cursor
        data = _request('GET', '/sandbox', params=params)
        if isinstance(data, dict):
            items = data.get('items', [])
            cursor = data.get('nextCursor')
        else:
            items = data or []
            cursor = None
        for item in items:
            item_labels = item.get('labels') or {}
            # Defensive client-side filter in case the API ignores the query.
            if item_labels.get(CLUSTER_LABEL) != cluster_name_on_cloud:
                continue
            sandboxes.append(item)
        if not cursor:
            return sandboxes


def get_sandbox(sandbox_id: str) -> Dict[str, Any]:
    return _request('GET', f'/sandbox/{sandbox_id}')


def _instance_type_to_create_body(instance_type: str,
                                  use_spot: bool) -> Dict[str, Any]:
    """Builds the sandbox create request body for an instance type.

    GPU instance types are named `<count>x-<GPU>` (e.g. `2x-H100`), CPU
    instance types `cpu-<vcpus>x-<mem>gb` (e.g. `cpu-4x-16gb`), matching
    the generated catalog.
    """
    body: Dict[str, Any] = {}
    if instance_type.startswith('cpu-'):
        if use_spot:
            raise DaytonaError(
                'Spot is only supported for GPU sandboxes on Daytona.')
        parts = instance_type[len('cpu-'):].split('-')
        cpus = int(parts[0].rstrip('x'))
        memory = int(parts[1].rstrip('gb'))
        body.update({'cpu': cpus, 'memory': memory})
        return body

    count_str, gpu_name = instance_type.split('x-', maxsplit=1)
    gpu_count = int(count_str)
    daytona_gpu = GPU_INSTANCE_TYPE_TO_DAYTONA_GPU.get(gpu_name)
    if daytona_gpu is None:
        raise DaytonaError(f'Unknown Daytona instance type: {instance_type}')
    memory_per_gpu = (CONSUMER_MEMORY_PER_GPU_GIB
                      if gpu_name in CONSUMER_GPUS else MEMORY_PER_GPU_GIB)
    body.update({
        'gpu': gpu_count,
        'gpuType': [daytona_gpu],
        'cpu': CPUS_PER_GPU * gpu_count,
        'memory': memory_per_gpu * gpu_count,
    })
    if use_spot:
        body['spot'] = True
    return body


def launch_sandbox(
    cluster_name_on_cloud: str,
    instance_type: str,
    region: str,
    use_spot: bool,
    disk_size: Optional[int] = None,
    image_id: Optional[str] = None,
) -> str:
    """Creates a sandbox for the cluster and returns its ID.

    The sandbox is labeled with the cluster name so that subsequent
    provisioner calls can find it. Auto-stop is disabled: SkyPilot manages
    the sandbox lifecycle (Daytona GPU sandboxes are deleted on stop).
    """
    body = _instance_type_to_create_body(instance_type, use_spot)
    is_gpu = 'gpu' in body
    if is_gpu:
        check_gpu_capacity(body['gpuType'][0], body['gpu'], use_spot)
    body['labels'] = {CLUSTER_LABEL: cluster_name_on_cloud}
    body['autoStopInterval'] = 0
    # GPU sandboxes must be ephemeral (deleted on stop); the create API
    # rejects them otherwise. SkyPilot never stops Daytona clusters (the
    # STOP feature is declared unsupported), so this only affects how the
    # platform would treat a stop, not SkyPilot's lifecycle.
    body['autoDeleteInterval'] = 0 if is_gpu else -1
    if disk_size is not None and is_gpu:
        # GPU sandboxes support up to 512 GiB disk per GPU. CPU sandboxes
        # have a much smaller tier-dependent per-sandbox disk cap (e.g.
        # 10 GiB), below SkyPilot's default disk_size, so the platform
        # default is used for them instead.
        body['disk'] = disk_size
    body['buildInfo'] = {
        'dockerfileContent': f'FROM {image_id or DEFAULT_IMAGE}'
    }
    if instance_type.startswith('cpu-') and region:
        # CPU sandboxes run in shared regions (e.g. us, eu). GPU sandboxes
        # run in the Earth region and ignore the target.
        body['target'] = region
    logger.debug(f'Creating Daytona sandbox: {body}')
    data = _request('POST', '/sandbox', body=body, timeout=_LAUNCH_TIMEOUT)
    sandbox_id = data.get('id')
    if not sandbox_id:
        raise DaytonaError(f'Sandbox creation returned no id: {data}')
    return sandbox_id


def wait_for_sandbox_started(sandbox_id: str,
                             timeout: int = _LAUNCH_TIMEOUT) -> None:
    """Waits until the sandbox reaches the `started` state."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        sandbox = get_sandbox(sandbox_id)
        state = (sandbox.get('state') or '').lower()
        if state == 'started':
            return
        if state in ('error', 'build_failed', 'destroyed', 'deleted'):
            reason = sandbox.get('errorReason')
            raise DaytonaError(
                f'Sandbox {sandbox_id} entered state {state!r}: {reason}')
        time.sleep(_POLL_INTERVAL)
    raise DaytonaError(
        f'Sandbox {sandbox_id} did not start within {timeout} seconds.')


def delete_sandbox(sandbox_id: str) -> None:
    """Deletes a sandbox. Safe to call on already-deleted sandboxes."""
    try:
        _request('DELETE', f'/sandbox/{sandbox_id}')
    except DaytonaError as e:
        if '404' in str(e):
            return
        raise


def create_ssh_token(sandbox_id: str) -> str:
    """Issues an SSH access token for a sandbox.

    The token is used as the SSH username against the Daytona SSH gateway:
    `ssh <token>@ssh.app.daytona.io`.
    """
    data = _request(
        'POST',
        f'/sandbox/{sandbox_id}/ssh-access',
        params={'expiresInMinutes': SSH_TOKEN_EXPIRES_MINUTES},
    )
    token = data.get('token')
    if not token:
        raise DaytonaError(f'SSH access response has no token: {data}')
    return token
