---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skypilot-api-sa
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skypilot-api-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skypilot-api-role-binding
subjects:
- kind: ServiceAccount
  name: skypilot-api-sa
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: skypilot-api-role
  apiGroup: rbac.authorization.k8s.io
