#FROM continuumio/miniconda3:22.11.1
FROM nvidia/cuda:12.2.0-devel-ubuntu20.04

# TODO(romilb): Investigate if this image can be consolidated with the skypilot
#  client image (`Dockerfile`)
# Set environment variable for non-interactive installations
ENV DEBIAN_FRONTEND=noninteractive


# Preconfigure tzdata
RUN echo "tzdata tzdata/Areas select America" | debconf-set-selections && \
    echo "tzdata tzdata/Zones/America select Adak" | debconf-set-selections

RUN apt update -y && apt install -y --no-install-recommends tzdata

# Initialize conda for root user, install ssh and other local dependencies
RUN apt update -y && \
    apt install sudo rsync openssh-server -y
    #sudo apt update -y && \
    #apt install rsync openssh-server -y
    #rm -rf /var/lib/apt/lists/*
    #apt remove -y python3 && \
    #conda init

# moved to setup_command
#RUN apt install openssh-server -y && \
#    mkdir -p /var/run/sshd && \
#    sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
#    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd && \
#    cd /etc/ssh/ && \
#    ssh-keygen -A


# Setup new user named sky and add to sudoers. Also add /opt/conda/bin to sudo path.
RUN useradd -m -s /bin/bash sky && \
    echo "sky ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    #echo 'Defaults        secure_path="/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"' > /etc/sudoers.d/sky
    echo 'Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"' > /etc/sudoers.d/sky


# Switch to sky user
USER sky

# Install SkyPilot pip dependencies
#RUN pip install wheel Click colorama cryptography jinja2 jsonschema && \
#    pip install networkx oauth2client pandas pendulum PrettyTable && \
#    pip install rich tabulate filelock && \
#    pip install packaging 'protobuf<4.0.0' pulp && \
#    pip install awscli boto3 pycryptodome==3.12.0 && \
#    pip install docker kubernetes

# Add /home/sky/.local/bin/ to PATH
RUN echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.bashrc

# Install SkyPilot. This is purposely separate from installing SkyPilot
# dependencies to optimize rebuild time
#COPY --chown=sky . /skypilot/sky/

# TODO(romilb): Installing SkyPilot may not be necessary since ray up will do it
#RUN cd /skypilot/ && \
#    sudo mv -v sky/setup_files/* . && \
#    pip install ".[aws]"

# Set PYTHONUNBUFFERED=1 to have Python print to stdout/stderr immediately
ENV PYTHONUNBUFFERED=1

# Set WORKDIR and initialize conda for sky user
WORKDIR /home/sky
#RUN conda init

