FROM nvidia/cuda:12.2.0-devel-ubuntu20.04

# TODO(romilb): Investigate if this image can be consolidated with the skypilot
#  client image (`Dockerfile`)
# Set environment variable for non-interactive installations
ENV DEBIAN_FRONTEND=noninteractive
# Preconfigure tzdata
RUN echo "tzdata tzdata/Areas select America" | debconf-set-selections && \
    echo "tzdata tzdata/Zones/America select Adak" | debconf-set-selections

RUN apt update -y && apt install -y --no-install-recommends tzdata

# Initialize conda for root user, install ssh and other local dependencies
RUN apt install sudo rsync openssh-server -y

# Setup new user named sky and add to sudoers. Also add /opt/conda/bin to sudo path.
RUN useradd -m -s /bin/bash sky && \
    echo "sky ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    echo 'Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"' > /etc/sudoers.d/sky


# Switch to sky user
USER sky

# Add /home/sky/.local/bin/ to PATH
RUN echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.bashrc

# Set PYTHONUNBUFFERED=1 to have Python print to stdout/stderr immediately
ENV PYTHONUNBUFFERED=1

# Set WORKDIR and initialize conda for sky user
WORKDIR /home/sky

