# Usage: Please refer to the README.md in this directory.

service:
  readiness_probe:
    path: /health
    initial_delay_seconds: 120

resources:
  ports: 9000
  cpus: 2+

workdir: examples/serve/misc/cancel

run: python3 server.py --port 9000
