version: '3.8'

services:
  invokeai:
    image: ghcr.io/invoke-ai/invokeai:v6.14.2-cuda
    container_name: invokeai
    restart: on-failure
    ports:
      - "9090:9090"
    volumes:
      - ~/invokeai:/invokeai
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN:-}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
