{
 "title": "SkyPilot vLLM Serving Metrics",
 "description": "Monitoring vLLM Inference Server deployed via SkyPilot SkyServe",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "endpoint_name",
    "label": "endpoint_name",
    "query": {
     "query": "label_values(app_kubernetes_io_name)"
    }
   },
   { "name": "model_name", "label": "model_name", "query": { "query": "label_values(model_name)" } },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "E2E Request Latency",
   "type": "timeseries",
   "description": "End to end request latency measured in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "sum(rate(vllm:e2e_request_latency_seconds_sum{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))\n/\nsum(rate(vllm:e2e_request_latency_seconds_count{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))",
     "legendFormat": "Average"
    },
    {
     "expr": "sum by (pod)(rate(vllm:e2e_request_latency_seconds_sum{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))\n/\nsum by (pod)(rate(vllm:e2e_request_latency_seconds_count{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Token Throughput",
   "type": "timeseries",
   "description": "Number of tokens processed per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(vllm:prompt_tokens_total{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))",
     "legendFormat": "Prompt Tokens/Sec"
    },
    {
     "expr": "sum(rate(vllm:generation_tokens_total{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))",
     "legendFormat": "Generation Tokens/Sec"
    },
    {
     "expr": "sum by (pod)(rate(vllm:prompt_tokens_total{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))",
     "legendFormat": "Prompt {{pod}}"
    },
    {
     "expr": "sum by (pod)(rate(vllm:generation_tokens_total{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))",
     "legendFormat": "Generation {{pod}}"
    }
   ]
  },
  {
   "title": "Inter Token Latency",
   "type": "timeseries",
   "description": "Inter token latency in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:inter_token_latency_seconds_bucket{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:inter_token_latency_seconds_bucket{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:inter_token_latency_seconds_bucket{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:inter_token_latency_seconds_bucket{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "sum(rate(vllm:inter_token_latency_seconds_sum{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))\n/\nsum(rate(vllm:inter_token_latency_seconds_count{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))",
     "legendFormat": "Mean"
    },
    {
     "expr": "sum by (pod)(rate(vllm:inter_token_latency_seconds_sum{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))\n/\nsum by (pod)(rate(vllm:inter_token_latency_seconds_count{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Scheduler State",
   "type": "timeseries",
   "description": "Number of requests in RUNNING, WAITING, and SWAPPED state",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(vllm:num_requests_running{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"})",
     "legendFormat": "Num Running"
    },
    {
     "expr": "sum(vllm:num_requests_waiting{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"})",
     "legendFormat": "Num Waiting"
    },
    {
     "expr": "sum by (pod)(vllm:num_requests_running{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"})",
     "legendFormat": "Running {{pod}}"
    },
    {
     "expr": "sum by (pod)(vllm:num_requests_waiting{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"})",
     "legendFormat": "Waiting {{pod}}"
    }
   ]
  },
  {
   "title": "Time To First Token Latency",
   "type": "timeseries",
   "description": "P50, P90, P95, and P99 TTFT latency in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "sum(rate(vllm:time_to_first_token_seconds_sum{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))\n/\nsum(rate(vllm:time_to_first_token_seconds_count{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))",
     "legendFormat": "Average"
    },
    {
     "expr": "sum by (pod)(rate(vllm:time_to_first_token_seconds_sum{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))\n/\nsum by (pod)(rate(vllm:time_to_first_token_seconds_count{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cache Utilization",
   "type": "timeseries",
   "description": "Percentage of used cache blocks by vLLM.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(vllm:kv_cache_usage_perc{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"})",
     "legendFormat": "KV Cache Usage"
    },
    {
     "expr": "avg by (pod)(vllm:kv_cache_usage_perc{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Prompt Length",
   "type": "heatmap",
   "description": "Heatmap of request prompt length",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_prompt_tokens_bucket{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Generation Length",
   "type": "heatmap",
   "description": "Heatmap of request generation length",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_generation_tokens_bucket{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Finish Reason",
   "type": "timeseries",
   "description": "Number of finished requests by their finish reason: either an EOS token was generated or the max sequence length was reached.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(finished_reason) (increase(vllm:request_success_total{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(vllm:request_queue_time_seconds_sum{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))\n/\nsum(rate(vllm:request_queue_time_seconds_count{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))",
     "legendFormat": "Mean queue time"
    },
    {
     "expr": "sum by (pod)(rate(vllm:request_queue_time_seconds_sum{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))\n/\nsum by (pod)(rate(vllm:request_queue_time_seconds_count{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Requests Prefill and Decode Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(vllm:request_prefill_time_seconds_sum{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval])",
     "legendFormat": "Prefill"
    },
    {
     "expr": "rate(vllm:request_decode_time_seconds_sum{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval])",
     "legendFormat": "Decode"
    }
   ]
  },
  {
   "title": "Max Generation Token in Sequence Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(vllm:request_max_num_generation_tokens_sum{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval])",
     "legendFormat": "Tokens"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "description": "Rate of successfully completed requests, aggregated across replicas.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(vllm:request_success_total{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))",
     "legendFormat": "req/s"
    },
    {
     "expr": "sum by (pod)(rate(vllm:request_success_total{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Queue Depth",
   "type": "timeseries",
   "description": "Number of requests waiting in the scheduler queue, aggregated across replicas.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(vllm:num_requests_waiting{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum by (pod)(vllm:num_requests_waiting{model_name=~\"$model_name\", cluster=~\"$cluster\", app_kubernetes_io_name=~\"$endpoint_name\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{cluster=~\"$cluster\", pod=~\"$endpoint_name-.+\"}",
     "legendFormat": "{{pod}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(DCGM_FI_DEV_FB_USED{cluster=~\"$cluster\", pod=~\"$endpoint_name-.+\"} / (DCGM_FI_DEV_FB_USED{cluster=~\"$cluster\", pod=~\"$endpoint_name-.+\"} + DCGM_FI_DEV_FB_FREE{cluster=~\"$cluster\", pod=~\"$endpoint_name-.+\"})) * 100",
     "legendFormat": "{{pod}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{cluster=~\"$cluster\", pod=~\"$endpoint_name-.+\"}",
     "legendFormat": "{{pod}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{cluster=~\"$cluster\", pod=~\"$endpoint_name-.+\"}",
     "legendFormat": "{{pod}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "CPU Usage (cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod, namespace) (\n  rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", container!=\"\", container!=\"POD\", pod=~\"$endpoint_name-.+\"}[5m])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod, namespace) (\n  container_memory_working_set_bytes{cluster=~\"$cluster\", container!=\"\", container!=\"POD\", pod=~\"$endpoint_name-.+\"}\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}