apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: prometheus
  name: skypilot-prometheus-server
  namespace: skypilot
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
  sessionAffinity: None
  type: ClusterIP
