name: go-reviewable

on:
    pull_request:
      branches:
        - master
        - 'releases/**'
      paths:
        - 'addons/fuse-proxy/**'

jobs:
  reviewable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Set up Go
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version: '1.23'
      - name: Run reviewable
        working-directory: addons/fuse-proxy
        run: make reviewable
