name: go-reviewable

on:
    pull_request:
      branches:
        - master
        - 'releases/**'
      paths:
        - 'addons/fuse-proxy/**'

jobs:
  reviewable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Run reviewable
        working-directory: addons/fuse-proxy
        run: make reviewable
