# This is needed for GitHub Actions for the "Waiting for status to be reported" problem,
# according to https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks
name: mypy

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    branches:
      - master
      - 'releases/**'
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No mypy to run"'
