name: Python Optimizer Dryrun Tests
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    branches:
      - master
      - 'releases/**'
  merge_group:

jobs:
  python-test:
    strategy:
      matrix:
        python-version: ["3.8"]
        test-path:
          # Group them based on running time to save CI time and resources
          - "tests/test_optimizer_dryruns.py -k \"partial\""
          - "tests/test_optimizer_dryruns.py -k \"not partial\""
        include:
          - test-path: "tests/test_optimizer_dryruns.py -k \"partial\""
            test-name: "Optimizer Dryruns Part 1"
          - test-path: "tests/test_optimizer_dryruns.py -k \"not partial\""
            test-name: "Optimizer Dryruns Part 2"
    runs-on: ubuntu-latest
    name: "Python Tests - ${{ matrix.test-name }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          uv venv --seed ~/test-env
          source ~/test-env/bin/activate
          uv pip install --prerelease=allow "azure-cli>=2.65.0"
          # Use -e to include examples and tests folder in the path for unit
          # tests to access them.
          uv pip install -e ".[all]"
          uv pip install pytest pytest-xdist pytest-env>=0.6 pytest-asyncio memory-profiler==0.61.0
      - name: Run tests with pytest
        env:
          TEST_PATH: ${{ matrix.test-path }}
          TEST_NAME: ${{ matrix.test-name }}
        run: |
          source ~/test-env/bin/activate
          if [[ "$TEST_NAME" == "No Parallel Tests" || "$TEST_NAME" == "Event Loop Lag Tests" ]]; then
            SKYPILOT_DISABLE_USAGE_COLLECTION=1 SKYPILOT_SKIP_CLOUD_IDENTITY_CHECK=1 eval "pytest -n 0 --dist no $TEST_PATH"
          else
            SKYPILOT_DISABLE_USAGE_COLLECTION=1 SKYPILOT_SKIP_CLOUD_IDENTITY_CHECK=1 eval "pytest -n 4 --dist worksteal $TEST_PATH"
          fi
