apiVersion: v1
kind: ServiceAccount
metadata:
  name: sky-airflow-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sky-airflow-sa-binding
subjects:
- kind: ServiceAccount
  name: sky-airflow-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
